/**
 * The two schemas must stay structurally identical.
 *
 * src/lib/db/schema.ts picks the real tables at runtime from DATABASE_URL but presents the
 * PostgreSQL types to TypeScript, because a dialect is a runtime value and types are not. That
 * trade only holds while both schemas declare the same tables, columns, nullability, defaults,
 * indexes and foreign keys. If they drift, a SQLite deployment silently gets row types describing
 * a database it does not have — no type error, no runtime error, just wrong data.
 *
 * schema.pg.ts is generated by scripts/generate-pg-schema.ts. This test is what catches someone
 * editing schema.sqlite.ts and not re-running it.
 */
import { describe, expect, it } from 'bun:test';
import { getTableConfig as getPgTableConfig, type PgTable } from 'drizzle-orm/pg-core';
import { getTableConfig as getSqliteTableConfig, type SQLiteTable } from 'drizzle-orm/sqlite-core';
import { is } from 'drizzle-orm';
import { PgTable as PgTableClass } from 'drizzle-orm/pg-core';
import { SQLiteTable as SQLiteTableClass } from 'drizzle-orm/sqlite-core';
import * as pgSchema from '../../src/lib/db/schema.pg';
import * as sqliteSchema from '../../src/lib/db/schema.sqlite';

type ColumnShape = {
  name: string;
  dataType: string;
  notNull: boolean;
  primary: boolean;
  hasDefault: boolean;
  default: unknown;
};

type IndexShape = { name: string; unique: boolean; columns: string[] };

type ForeignKeyShape = {
  columns: string[];
  foreignTable: string;
  foreignColumns: string[];
  onDelete: string | undefined;
};

type TableShape = {
  name: string;
  columns: ColumnShape[];
  indexes: IndexShape[];
  foreignKeys: ForeignKeyShape[];
};

function describeTable(config: any): TableShape {
  const columns: ColumnShape[] = config.columns
    .map((column: any) => ({
      name: column.name,
      dataType: column.dataType,
      notNull: column.notNull,
      primary: column.primary,
      hasDefault: column.hasDefault,
      default: column.default,
    }))
    .sort((a: ColumnShape, b: ColumnShape) => a.name.localeCompare(b.name));

  const indexes: IndexShape[] = config.indexes
    .map((index: any) => ({
      name: index.config.name,
      unique: Boolean(index.config.unique),
      columns: index.config.columns.map((column: any) => column.name),
    }))
    .sort((a: IndexShape, b: IndexShape) => a.name.localeCompare(b.name));

  const foreignKeys: ForeignKeyShape[] = config.foreignKeys
    .map((foreignKey: any) => {
      const reference = foreignKey.reference();
      return {
        columns: reference.columns.map((column: any) => column.name),
        foreignTable: reference.foreignTable[Symbol.for('drizzle:Name')] as string,
        foreignColumns: reference.foreignColumns.map((column: any) => column.name),
        onDelete: foreignKey.onDelete,
      };
    })
    .sort((a: ForeignKeyShape, b: ForeignKeyShape) =>
      a.columns.join().localeCompare(b.columns.join()),
    );

  return { name: config.name, columns, indexes, foreignKeys };
}

function sqliteTables(): Map<string, TableShape> {
  const out = new Map<string, TableShape>();
  for (const [key, value] of Object.entries(sqliteSchema)) {
    if (!is(value, SQLiteTableClass)) continue;
    out.set(key, describeTable(getSqliteTableConfig(value as SQLiteTable)));
  }
  return out;
}

function pgTables(): Map<string, TableShape> {
  const out = new Map<string, TableShape>();
  for (const [key, value] of Object.entries(pgSchema)) {
    if (!is(value, PgTableClass)) continue;
    out.set(key, describeTable(getPgTableConfig(value as PgTable)));
  }
  return out;
}

describe('SQLite and PostgreSQL schemas are structurally identical', () => {
  const sqlite = sqliteTables();
  const postgres = pgTables();

  it('exports the same table bindings', () => {
    expect([...postgres.keys()].sort()).toEqual([...sqlite.keys()].sort());
  });

  it('finds a non-trivial number of tables', () => {
    // Guards the two checks above from passing vacuously if an import ever resolves to {}.
    expect(sqlite.size).toBeGreaterThan(20);
  });

  for (const [binding, sqliteShape] of sqliteTables()) {
    describe(binding, () => {
      it('has the same SQL table name', () => {
        expect(postgres.get(binding)?.name).toBe(sqliteShape.name);
      });

      it('has the same columns, nullability and defaults', () => {
        expect(postgres.get(binding)?.columns).toEqual(sqliteShape.columns);
      });

      it('has the same indexes', () => {
        expect(postgres.get(binding)?.indexes).toEqual(sqliteShape.indexes);
      });

      it('has the same foreign keys', () => {
        expect(postgres.get(binding)?.foreignKeys).toEqual(sqliteShape.foreignKeys);
      });
    });
  }
});

describe('scripts/generate-pg-schema.ts output is current', () => {
  it('produces exactly the committed schema.pg.ts', async () => {
    const { generate } = await import('../../scripts/generate-pg-schema');
    const source = await Bun.file('src/lib/db/schema.sqlite.ts').text();
    const committed = (await Bun.file('src/lib/db/schema.pg.ts').text()).replace(/\r\n/g, '\n');
    // Byte-exact, not normalized: the generator formats through biome, so a mismatch means the
    // generated file is genuinely stale (or was hand-edited) rather than just differently wrapped.
    expect(generate(source)).toBe(committed);
  });
});
