#!/usr/bin/env bash
# Prepares the runner before any test file executes:
#
#   1. waits for the CPM API and for Pebble,
#   2. signs in as the seeded admin and mints a bearer token for the suite,
#   3. builds the CA bundle the client uses to verify Caddy's certificates,
#   4. points CPM's ACME settings at Pebble, so every auto-managed proxy host
#      in the suite gets a real, properly-validated certificate without the
#      network ever leaving the rig.
#
# Sourced state lands in $STATE_DIR and is read by lib.sh.
set -uo pipefail

SUITE_NAME=bootstrap
# shellcheck source=lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

PEBBLE_MGMT="${PEBBLE_MGMT:-https://pebble:15000}"
PEBBLE_DIRECTORY="${PEBBLE_DIRECTORY:-https://pebble:14000/dir}"
PEBBLE_ENDPOINT_CA=/certs/pebble-ca.crt.pem
COOKIE_JAR="$STATE_DIR/cookies.txt"

die() { printf '%sbootstrap: %s%s\n' "$C_RED" "$*" "$C_OFF" >&2; exit 1; }

# ── 1. Wait for the moving parts ────────────────────────────────────────────

banner "bootstrap"

wait_for "the CPM API" 120 curl -sSf --max-time 5 -o /dev/null "$CPM_API/api/health" \
  || die "web never became healthy at $CPM_API"
info "CPM API is up"

wait_for "Pebble's directory" 120 \
  curl -sSf --max-time 5 -o /dev/null --cacert "$PEBBLE_ENDPOINT_CA" "$PEBBLE_DIRECTORY" \
  || die "pebble never served $PEBBLE_DIRECTORY"
info "Pebble ACME directory is up"

# ── 2. Sign in and mint an API token ────────────────────────────────────────

rm -f "$COOKIE_JAR"

status=$(cpm_sign_in "$CPM_API" "$COOKIE_JAR" "$CPM_ADMIN_USER" "$CPM_ADMIN_PASSWORD")
[ "$status" = "200" ] || die "admin sign-in failed (HTTP $status): $SIGN_IN_BODY"
info "signed in as $CPM_ADMIN_USER"

cpm_mint_token "$CPM_API" "$COOKIE_JAR" "docker-test-suite" >"$TOKEN_FILE"
[ -s "$TOKEN_FILE" ] || die "could not mint an API token — the response carried no raw_token"
chmod 600 "$TOKEN_FILE"
info "minted an API token for the suite"

# ── 3. Build the client's trust store ───────────────────────────────────────
#
# Two unrelated CAs end up in here: the one signing Pebble's own HTTPS endpoint
# (generated by certgen) and the one Pebble issues from (generated by Pebble at
# startup, which is why it has to be fetched rather than baked in).

: >"$CA_BUNDLE"
# The bundle is rebuilt from scratch, so the "already added" markers that
# trust_ca leaves behind have to go with it — otherwise a second run in the
# same container would skip re-adding the local CAs and every test that relies
# on an imported certificate would fail to verify.
rm -f "$STATE_DIR"/.trusted-*
cat "$PEBBLE_ENDPOINT_CA" >>"$CA_BUNDLE"

roots_ok=0
for index in 0 1; do
  if curl -sSf --max-time 10 --cacert "$PEBBLE_ENDPOINT_CA" \
      "$PEBBLE_MGMT/roots/$index" >>"$CA_BUNDLE" 2>/dev/null; then
    roots_ok=1
  fi
done
[ "$roots_ok" = "1" ] || die "could not fetch Pebble's issuing root from $PEBBLE_MGMT/roots/0"

# Pebble issues from an intermediate; Caddy staples it, but fetching it too
# keeps `openssl verify` usable directly against the bundle.
curl -sSf --max-time 10 --cacert "$PEBBLE_ENDPOINT_CA" \
  "$PEBBLE_MGMT/intermediates/0" >>"$CA_BUNDLE" 2>/dev/null || true

info "CA bundle has $(grep -c 'BEGIN CERTIFICATE' "$CA_BUNDLE") certificate(s)"

# ── 4. Point CPM at the in-network ACME server ──────────────────────────────

acme_body=$(jq -nc --arg url "$PEBBLE_DIRECTORY" --rawfile root "$PEBBLE_ENDPOINT_CA" \
  '{caUrl:$url, caRootPem:$root}')
api PUT "/api/v1/settings/acme" "$acme_body"
[ "$API_STATUS" = "200" ] || die "could not save ACME settings (HTTP $API_STATUS): $API_BODY"

general_body=$(jq -nc --arg d "$TEST_DOMAIN" '{primaryDomain:$d, acmeEmail:"docker-tests@cpm.test"}')
api PUT "/api/v1/settings/general" "$general_body"
[ "$API_STATUS" = "200" ] || die "could not save general settings (HTTP $API_STATUS): $API_BODY"

info "CPM will issue certificates from $PEBBLE_DIRECTORY"

# ── 4b. Snapshot the declared API surface ───────────────────────────────────
#
# run-tests.sh measures how much of it the suite drove. Taken from the running
# instance rather than the repo so the report always describes the build under
# test.

api GET /api/v1/openapi.json
if [ "$API_STATUS" = "200" ]; then
  printf '%s' "$API_BODY" >"$SPEC_FILE"
  info "API surface: $(jq '[.paths[] | keys[]] | length' <"$SPEC_FILE" 2>/dev/null) documented operations"
else
  rm -f "$SPEC_FILE"
  info "could not fetch the OpenAPI document (HTTP $API_STATUS) — skipping API coverage"
fi

# ── 5. Prove the whole chain works before running any test ──────────────────
#
# If issuance is broken, every HTTPS assertion in the suite fails for the same
# uninformative reason. Catch it here instead, with one host that is created
# and torn down immediately.

probe_domain=$(domain_for "bootstrap-probe")
create_host "$(jq -nc --arg d "$probe_domain" \
  '{name:"bootstrap probe", domains:[$d], upstreams:["origin-a:8080"]}')" \
  || die "could not create the probe proxy host (HTTP $API_STATUS): $API_BODY"

if wait_for_https "$probe_domain" 120; then
  info "end-to-end certificate issuance verified against $probe_domain"
else
  die "Caddy never obtained a certificate for $probe_domain — check 'docker compose logs caddy pebble'"
fi

printf '%sbootstrap complete%s\n' "$C_GREEN" "$C_OFF"
