/**
 * Derives src/lib/db/schema.sqlite.ts from src/lib/db/schema.pg.ts.
 *
 * PostgreSQL stays the hand-edited source of truth. The mirror is mechanical because the schema
 * uses only four shapes - serial primary key, integer, text and boolean - each with one obvious
 * sqlite-core counterpart. Run after editing the PostgreSQL schema:
 *
 *   bun scripts/generate-sqlite-schema.ts
 *
 * tests/unit/db-schema-parity.test.ts fails if this was not re-run.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const SOURCE = resolve(import.meta.dir, "../src/lib/db/schema.pg.ts");
const TARGET = resolve(import.meta.dir, "../src/lib/db/schema.sqlite.ts");

const HEADER = `// Code generated by scripts/generate-sqlite-schema.ts. DO NOT EDIT.
// Edit src/lib/db/schema.pg.ts and re-run \`bun scripts/generate-sqlite-schema.ts\`.
`;

export function toSqliteSchema(source: string): string {
  let out = source;

  // The source's own header describes the source, not this file.
  out = out.replace(/^(\/\/.*\n)+/, "");

  // serial -> INTEGER PRIMARY KEY AUTOINCREMENT. Both infer `number` and are optional on insert.
  out = out.replace(
    /\bserial\((".*?")\)\.primaryKey\(\)/g,
    "integer($1).primaryKey({ autoIncrement: true })",
  );
  out = out.replace(/\bboolean\((".*?")\)/g, 'integer($1, { mode: "boolean" })');
  out = out.replace(/\bvarchar\((".*?"), \{ length: (\d+) \}\)/g, "text($1, { length: $2 })");
  out = out.replace(/\bpgTable\(/g, "sqliteTable(");
  out = out.replace(/from "\.\/columns\.pg"/g, 'from "./columns.sqlite"');

  // Emit only the imports the body uses, so biome's noUnusedImports stays quiet.
  const candidates = ["index", "integer", "sqliteTable", "text", "uniqueIndex"];
  const body = out.replace(/^import \{[^}]*\} from "drizzle-orm\/pg-core";\n/m, "");
  const used = candidates.filter((name) => new RegExp(`\\b${name}\\(`).test(body));
  const importLine = `import { ${used.join(", ")} } from "drizzle-orm/sqlite-core";`;
  out = out.replace(/^import \{[^}]*\} from "drizzle-orm\/pg-core";\n/m, `${importLine}\n`);

  for (const leftover of ["serial(", "boolean(", "varchar(", "pgTable(", "pg-core"]) {
    if (out.includes(leftover)) {
      throw new Error(`schema.pg.ts uses ${leftover} in a shape this generator does not handle.`);
    }
  }

  return HEADER + out;
}

/** Through biome, so the file on disk is exactly what `bun run format` would leave. */
export function formatWithBiome(source: string): string {
  const result = Bun.spawnSync(["bunx", "biome", "format", "--stdin-file-path=schema.sqlite.ts"], {
    stdin: Buffer.from(source, "utf8"),
    stdout: "pipe",
    stderr: "pipe",
  });
  if (result.exitCode !== 0) {
    throw new Error(`biome format failed: ${result.stderr.toString()}`);
  }
  // The repo is LF-only and biome emits CRLF on Windows.
  return result.stdout.toString().replace(/\r\n/g, "\n");
}

/** The exact bytes src/lib/db/schema.sqlite.ts should contain. */
export function generate(source: string = readFileSync(SOURCE, "utf8")): string {
  return formatWithBiome(toSqliteSchema(source));
}

if (import.meta.main) {
  writeFileSync(TARGET, generate(), "utf8");
  console.log(`Wrote ${TARGET}`);
}
