/**
 * Derives src/lib/db/schema.pg.ts from src/lib/db/schema.sqlite.ts.
 *
 * The SQLite schema stays the hand-edited source of truth: it is the default backend and the one
 * every existing deployment runs. The PostgreSQL mirror is mechanical because the schema only uses
 * four shapes — autoincrement integer primary key, integer, text, and integer-as-boolean — each of
 * which has a single obvious pg-core counterpart.
 *
 * Run after editing the SQLite schema:
 *   bun scripts/generate-pg-schema.ts
 *
 * tests/unit/db-schema-parity.test.ts compares the two modules structurally and fails if this was
 * not re-run, so forgetting is caught in CI rather than at a customer's first PostgreSQL boot.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const SOURCE = resolve(process.cwd(), "src/lib/db/schema.sqlite.ts");
const TARGET = resolve(process.cwd(), "src/lib/db/schema.pg.ts");

const HEADER = `// Code generated by scripts/generate-pg-schema.ts. DO NOT EDIT.
// Edit src/lib/db/schema.sqlite.ts and re-run \`bun scripts/generate-pg-schema.ts\`.
`;

export function toPostgresSchema(source: string): string {
  let out = source;

  // 1. INTEGER PRIMARY KEY AUTOINCREMENT -> serial. Both infer \`number\` and both make the column
  //    optional on insert, so row types are unchanged.
  out = out.replace(
    /\binteger\((".*?")\)\.primaryKey\(\{ autoIncrement: true \}\)/g,
    "serial($1).primaryKey()",
  );

  // 2. SQLite stores booleans as 0/1 in an integer column; Postgres has a real boolean type.
  out = out.replace(/\binteger\((".*?"), \{ mode: "boolean" \}\)/g, "boolean($1)");

  // 3. pg-core's \`text\` takes no length; a bounded string is \`varchar\`.
  out = out.replace(/\btext\((".*?"), \{ length: (\d+) \}\)/g, "varchar($1, { length: $2 })");

  // 4. Table builder.
  out = out.replace(/\bsqliteTable\(/g, "pgTable(");

  // 5. Shared custom column types are built on a dialect's own `customType`, so each schema takes
  //    them from its own module.
  out = out.replace(/from "\.\/columns\.sqlite"/g, 'from "./columns.pg"');

  // 6. Imports — emit only what the transformed body actually references, so biome's
  //    noUnusedImports stays quiet as the schema changes.
  const candidates = [
    "boolean",
    "index",
    "integer",
    "pgTable",
    "serial",
    "text",
    "uniqueIndex",
    "varchar",
  ];
  const body = out.slice(out.indexOf("\n"));
  const used = candidates.filter((name) => new RegExp(`\\b${name}\\b`).test(body));
  const importLine = `import { ${used.join(", ")} } from "drizzle-orm/pg-core";`;

  out = out.replace(/^import \{[^}]*\} from "drizzle-orm\/sqlite-core";\n/, `${importLine}\n`);

  return HEADER + out;
}

/**
 * The transform's output through biome, so what lands on disk is byte-identical to what
 * `bun run format` would leave behind. Without this the generated file fails format:check the
 * moment a rewritten line crosses the print width.
 */
export function formatWithBiome(source: string): string {
  const result = Bun.spawnSync(["bunx", "biome", "format", "--stdin-file-path=schema.pg.ts"], {
    stdin: Buffer.from(source, "utf8"),
    stdout: "pipe",
    stderr: "pipe",
  });
  if (result.exitCode !== 0) {
    throw new Error(`biome format failed: ${result.stderr.toString()}`);
  }
  // The repo is LF-only and biome emits CRLF on Windows.
  return result.stdout.toString().replace(/\r\n/g, "\n");
}

/** The exact bytes src/lib/db/schema.pg.ts should contain for a given SQLite schema. */
export function generate(source: string): string {
  return formatWithBiome(toPostgresSchema(source));
}

if (import.meta.main) {
  writeFileSync(TARGET, generate(readFileSync(SOURCE, "utf8")), "utf8");
  console.log(`Wrote ${TARGET}`);
}
