// Code generated by scripts/generate-sqlite-schema.ts. DO NOT EDIT.
// Edit src/lib/db/schema.pg.ts and re-run `bun scripts/generate-sqlite-schema.ts`.
import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
import { isoTimestamp } from "./columns.sqlite";

export const users = sqliteTable(
  "users",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    email: text("email").notNull(),
    name: text("name"),
    passwordHash: text("passwordHash"),
    // When the login password was last set. Null for a user without one, and for one whose password
    // predates this column - the credential account's updatedAt cannot stand in for it, because the
    // environment-seeded admin rewrites that row on every start.
    passwordChangedAt: isoTimestamp("passwordChangedAt"),
    role: text("role").notNull().default("user"),
    provider: text("provider"),
    subject: text("subject"),
    avatarUrl: text("avatarUrl"),
    status: text("status").notNull().default("active"),
    username: text("username"),
    displayUsername: text("displayUsername"),
    emailVerified: integer("emailVerified", { mode: "boolean" }).notNull().default(false),
    createdAt: isoTimestamp("createdAt").notNull(),
    updatedAt: isoTimestamp("updatedAt").notNull(),
  },
  (table) => ({
    emailUnique: uniqueIndex("users_email_unique").on(table.email),
  }),
);

// Auth tables use camelCase DB columns to match Better Auth's Kysely adapter.
export const sessions = sqliteTable(
  "sessions",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    token: text("token").notNull(),
    expiresAt: isoTimestamp("expiresAt").notNull(),
    ipAddress: text("ipAddress"),
    userAgent: text("userAgent"),
    // Which IdP session this one came from, when it came from one at all. OIDC back-channel
    // logout names the session to end by its `sid`, which is only unique within an issuer - so
    // the provider is stored beside it rather than matching on `sid` alone. Both stay null for
    // credential sign-ins and for providers that issue no `sid`.
    oidcProviderId: text("oidcProviderId"),
    oidcSid: text("oidcSid"),
    createdAt: isoTimestamp("createdAt").notNull(),
    updatedAt: isoTimestamp("updatedAt").notNull(),
  },
  (table) => ({
    tokenUnique: uniqueIndex("sessions_token_unique").on(table.token),
    userIdx: index("sessions_user_idx").on(table.userId),
    oidcSessionIdx: index("sessions_oidc_session_idx").on(table.oidcProviderId, table.oidcSid),
  }),
);

export const accounts = sqliteTable(
  "accounts",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    accountId: text("accountId").notNull(),
    providerId: text("providerId").notNull(),
    accessToken: text("accessToken"),
    refreshToken: text("refreshToken"),
    idToken: text("idToken"),
    accessTokenExpiresAt: isoTimestamp("accessTokenExpiresAt"),
    refreshTokenExpiresAt: isoTimestamp("refreshTokenExpiresAt"),
    scope: text("scope"),
    password: text("password"),
    createdAt: isoTimestamp("createdAt").notNull(),
    updatedAt: isoTimestamp("updatedAt").notNull(),
  },
  (table) => ({
    providerAccountIdx: uniqueIndex("accounts_provider_account_idx").on(
      table.providerId,
      table.accountId,
    ),
    userIdx: index("accounts_user_idx").on(table.userId),
  }),
);

export const verifications = sqliteTable("verifications", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: isoTimestamp("expiresAt").notNull(),
  createdAt: isoTimestamp("createdAt"),
  updatedAt: isoTimestamp("updatedAt"),
});

export const oauthProviders = sqliteTable(
  "oauth_providers",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    type: text("type").notNull().default("oidc"),
    clientId: text("clientId").notNull(),
    clientSecret: text("clientSecret").notNull(),
    issuer: text("issuer"),
    authorizationUrl: text("authorizationUrl"),
    tokenUrl: text("tokenUrl"),
    userinfoUrl: text("userinfoUrl"),
    scopes: text("scopes").notNull().default("openid email profile"),
    autoLink: integer("autoLink", { mode: "boolean" }).notNull().default(false),
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    source: text("source").notNull().default("ui"),
    // ── OIDC group mapping ────────────────────────────────────────────────
    // Claim holding the user's groups. Dot-separated paths address nested claims (e.g.
    // "resource_access.cpm.roles").
    groupsClaim: text("groupsClaim").notNull().default("groups"),
    // Convention prefix: with "CPM_", membership of "CPM_Admin" grants admin.
    groupPrefix: text("groupPrefix"),
    roleMappingEnabled: integer("roleMappingEnabled", { mode: "boolean" }).notNull().default(false),
    // Explicit overrides; when unset they are derived from groupPrefix.
    adminGroup: text("adminGroup"),
    operatorGroup: text("operatorGroup"),
    userGroup: text("userGroup"),
    viewerGroup: text("viewerGroup"),
    // Role assigned when no role group matched.
    defaultRole: text("defaultRole").notNull().default("user"),
    // Mirror the remaining prefixed IdP groups into CPM groups.
    syncGroups: integer("syncGroups", { mode: "boolean" }).notNull().default(false),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    nameUnique: uniqueIndex("oauth_providers_name_unique").on(table.name),
  }),
);

export const oauthStates = sqliteTable(
  "oauth_states",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    state: text("state").notNull(),
    codeVerifier: text("codeVerifier").notNull(),
    redirectTo: text("redirectTo"),
    createdAt: text("createdAt").notNull(),
    expiresAt: text("expiresAt").notNull(),
  },
  (table) => ({
    stateUnique: uniqueIndex("oauth_state_unique").on(table.state),
  }),
);

export const pendingOAuthLinks = sqliteTable(
  "pending_oauth_links",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    userId: integer("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    provider: text("provider", { length: 50 }).notNull(),
    userEmail: text("userEmail").notNull(), // Email of the user who initiated linking
    createdAt: text("createdAt").notNull(),
    expiresAt: text("expiresAt").notNull(),
  },
  (table) => ({
    // Ensure only one pending link per user per provider (prevents race conditions)
    userProviderUnique: uniqueIndex("pending_oauth_user_provider_unique").on(
      table.userId,
      table.provider,
    ),
  }),
);

export const settings = sqliteTable("settings", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  updatedAt: text("updatedAt").notNull(),
});

/**
 * Settings edited but not yet applied, held per operator.
 *
 * Same `key` and serialized `value` as `settings`, so a staged row is a drop-in for the stored one
 * and the read path parses both identically. Scoped by user because two admins editing at once
 * must not see each other's half-finished work land in their own apply - the row moves into
 * `settings` only when its owner applies.
 */
export const settingsStaged = sqliteTable(
  "settings_staged",
  {
    key: text("key").notNull(),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    value: text("value").notNull(),
    stagedAt: text("stagedAt").notNull(),
  },
  (table) => ({
    pk: uniqueIndex("settings_staged_user_key_idx").on(table.userId, table.key),
  }),
);

/**
 * One row per apply, so an operator can see what changed and when it reached Caddy.
 *
 * `id` is the revision number the UI shows. `summary` is the human-readable change list rendered
 * at apply time rather than derived later: the settings it describes have moved on by then, and a
 * history that re-reads current values would narrate the present, not what happened.
 */
export const settingsRevisions = sqliteTable("settings_revisions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  appliedBy: integer("appliedBy").references(() => users.id, { onDelete: "set null" }),
  appliedByName: text("appliedByName"),
  summary: text("summary").notNull(),
  keys: text("keys").notNull(),
  outcome: text("outcome").notNull(),
  error: text("error"),
  appliedAt: text("appliedAt").notNull(),
});

/**
 * Agents this controller has paired with.
 *
 * No address, because the controller never dials one: agents connect inbound and hold an event
 * stream open, so whether an agent is reachable is a question about `lib/agent/registry.ts` and
 * this table cannot answer it. What lives here is the half that must outlive a restart - who the
 * agent is, and the secret it signs with.
 *
 * `agentId` is the identity the agent asserts on every request and the key pairing upserts on, so
 * an agent that re-pairs replaces its row rather than accumulating one per attempt.
 */
export const agents = sqliteTable(
  "agents",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    /** The agent's own stable id, minted once on its host and reported at pairing. */
    agentId: text("agentId").notNull(),
    /** Shared secret, encrypted at rest. Never leaves the server. */
    secret: text("secret").notNull(),
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    /**
     * This agent's own Caddy build selection, as JSON, or null to follow the fleet default.
     *
     * Null rather than a copy of the default: an agent that has never been configured separately
     * must keep tracking the fleet selection, so enabling a module for everyone does not silently
     * skip the hosts nobody thought to open.
     */
    buildSettings: text("buildSettings"),
    lastSeenAt: text("lastSeenAt"),
    lastError: text("lastError"),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    agentIdUnique: uniqueIndex("agents_agentId_unique").on(table.agentId),
  }),
);

export const accessLists = sqliteTable("access_lists", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  description: text("description"),
  createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
  createdAt: text("createdAt").notNull(),
  updatedAt: text("updatedAt").notNull(),
});

export const accessListEntries = sqliteTable(
  "access_list_entries",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    accessListId: integer("accessListId")
      .references(() => accessLists.id, { onDelete: "cascade" })
      .notNull(),
    username: text("username").notNull(),
    passwordHash: text("passwordHash").notNull(),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    accessListIdIdx: index("access_list_entries_list_idx").on(table.accessListId),
  }),
);

export const certificates = sqliteTable("certificates", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  type: text("type").notNull(),
  domainNames: text("domainNames").notNull(),
  autoRenew: integer("autoRenew", { mode: "boolean" }).notNull().default(true),
  providerOptions: text("providerOptions"),
  certificatePem: text("certificatePem"),
  privateKeyPem: text("privateKeyPem"),
  createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
  createdAt: text("createdAt").notNull(),
  updatedAt: text("updatedAt").notNull(),
});

export const caCertificates = sqliteTable("ca_certificates", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  certificatePem: text("certificatePem").notNull(),
  privateKeyPem: text("privateKeyPem"),
  createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
  createdAt: text("createdAt").notNull(),
  updatedAt: text("updatedAt").notNull(),
});

export const issuedClientCertificates = sqliteTable(
  "issued_client_certificates",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    caCertificateId: integer("caCertificateId")
      .references(() => caCertificates.id, { onDelete: "cascade" })
      .notNull(),
    commonName: text("commonName").notNull(),
    serialNumber: text("serialNumber").notNull(),
    fingerprintSha256: text("fingerprintSha256").notNull(),
    certificatePem: text("certificatePem").notNull(),
    validFrom: text("validFrom").notNull(),
    validTo: text("validTo").notNull(),
    revokedAt: text("revokedAt"),
    createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    caCertificateIdx: index("issued_client_certificates_ca_idx").on(table.caCertificateId),
    revokedAtIdx: index("issued_client_certificates_revoked_at_idx").on(table.revokedAt),
  }),
);

export const proxyHosts = sqliteTable("proxy_hosts", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  domains: text("domains").notNull(),
  upstreams: text("upstreams").notNull(),
  certificateId: integer("certificateId").references(() => certificates.id, {
    onDelete: "set null",
  }),
  accessListId: integer("accessListId").references(() => accessLists.id, { onDelete: "set null" }),
  ownerUserId: integer("ownerUserId").references(() => users.id, { onDelete: "set null" }),
  sslForced: integer("sslForced", { mode: "boolean" }).notNull().default(true),
  hstsEnabled: integer("hstsEnabled", { mode: "boolean" }).notNull().default(true),
  hstsSubdomains: integer("hstsSubdomains", { mode: "boolean" }).notNull().default(false),
  allowWebsocket: integer("allowWebsocket", { mode: "boolean" }).notNull().default(true),
  preserveHostHeader: integer("preserveHostHeader", { mode: "boolean" }).notNull().default(true),
  meta: text("meta"),
  enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
  createdAt: text("createdAt").notNull(),
  updatedAt: text("updatedAt").notNull(),
  skipHttpsHostnameValidation: integer("skipHttpsHostnameValidation", { mode: "boolean" })
    .notNull()
    .default(false),
});

export const apiTokens = sqliteTable(
  "api_tokens",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    tokenHash: text("tokenHash").notNull(),
    createdBy: integer("createdBy")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    createdAt: text("createdAt").notNull(),
    lastUsedAt: text("lastUsedAt"),
    expiresAt: text("expiresAt"),
  },
  (table) => ({
    tokenHashUnique: uniqueIndex("api_tokens_token_hash_unique").on(table.tokenHash),
  }),
);

export const auditEvents = sqliteTable("audit_events", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userId: integer("userId").references(() => users.id, { onDelete: "set null" }),
  action: text("action").notNull(),
  entityType: text("entityType").notNull(),
  entityId: integer("entityId"),
  summary: text("summary"),
  data: text("data"),
  createdAt: text("createdAt").notNull(),
});

// traffic_events and waf_events live in ClickHouse - see src/lib/clickhouse/client.ts. The
// parsers that fill them, and their read offsets, live in the agent: the Caddy log is a file on
// the agent's host, which a controller elsewhere cannot read at all.

// ── mTLS RBAC ──────────────────────────────────────────────────────────

export const mtlsRoles = sqliteTable(
  "mtls_roles",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    description: text("description"),
    createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    nameUnique: uniqueIndex("mtls_roles_name_unique").on(table.name),
  }),
);

// Named SecLang snippets the global WAF and each host select by id (upstream #149).
export const wafPresets = sqliteTable(
  "waf_presets",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    description: text("description"),
    directives: text("directives").notNull(),
    createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    nameUnique: uniqueIndex("waf_presets_name_unique").on(table.name),
  }),
);

// CRS plugins installed from the plugin registry, pinned to the release they were fetched at. The
// rule files are stored rather than fetched per apply, so a config build never waits on GitHub.
export const crsPlugins = sqliteTable(
  "crs_plugins",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    repository: text("repository").notNull(),
    version: text("version").notNull(),
    description: text("description"),
    ruleIdStart: integer("ruleIdStart").notNull(),
    ruleIdEnd: integer("ruleIdEnd").notNull(),
    configRules: text("configRules").notNull(),
    beforeRules: text("beforeRules").notNull(),
    afterRules: text("afterRules").notNull(),
    // The operator's edit of the -config file; null runs the upstream one. Survives an update.
    configOverride: text("configOverride"),
    createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    nameUnique: uniqueIndex("crs_plugins_name_unique").on(table.name),
  }),
);

export const mtlsCertificateRoles = sqliteTable(
  "mtls_certificate_roles",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    issuedClientCertificateId: integer("issuedClientCertificateId")
      .references(() => issuedClientCertificates.id, { onDelete: "cascade" })
      .notNull(),
    mtlsRoleId: integer("mtlsRoleId")
      .references(() => mtlsRoles.id, { onDelete: "cascade" })
      .notNull(),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    certRoleUnique: uniqueIndex("mtls_cert_role_unique").on(
      table.issuedClientCertificateId,
      table.mtlsRoleId,
    ),
    roleIdx: index("mtls_certificate_roles_role_idx").on(table.mtlsRoleId),
  }),
);

export const mtlsAccessRules = sqliteTable(
  "mtls_access_rules",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    proxyHostId: integer("proxyHostId")
      .references(() => proxyHosts.id, { onDelete: "cascade" })
      .notNull(),
    pathPattern: text("pathPattern").notNull(),
    allowedRoleIds: text("allowedRoleIds").notNull().default("[]"),
    allowedCertIds: text("allowedCertIds").notNull().default("[]"),
    denyAll: integer("denyAll", { mode: "boolean" }).notNull().default(false),
    priority: integer("priority").notNull().default(0),
    description: text("description"),
    createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    proxyHostIdx: index("mtls_access_rules_proxy_host_idx").on(table.proxyHostId),
    hostPathUnique: uniqueIndex("mtls_access_rules_host_path_unique").on(
      table.proxyHostId,
      table.pathPattern,
    ),
  }),
);

// ── Forward Auth (IdP) ───────────────────────────────────────────────

export const groups = sqliteTable(
  "groups",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    description: text("description"),
    createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
    // "ui" for operator-managed groups, "oidc" for groups created by an IdP group sync. Only
    // "oidc" group membership is reconciled on sign-in.
    source: text("source").notNull().default("ui"),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    nameUnique: uniqueIndex("groups_name_unique").on(table.name),
  }),
);

export const groupMembers = sqliteTable(
  "group_members",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    groupId: integer("groupId")
      .references(() => groups.id, { onDelete: "cascade" })
      .notNull(),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    memberUnique: uniqueIndex("group_members_unique").on(table.groupId, table.userId),
    userIdx: index("group_members_user_idx").on(table.userId),
  }),
);

export const forwardAuthAccess = sqliteTable(
  "forward_auth_access",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    proxyHostId: integer("proxyHostId")
      .references(() => proxyHosts.id, { onDelete: "cascade" })
      .notNull(),
    userId: integer("userId").references(() => users.id, { onDelete: "cascade" }),
    groupId: integer("groupId").references(() => groups.id, { onDelete: "cascade" }),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    hostIdx: index("faa_host_idx").on(table.proxyHostId),
    userUnique: uniqueIndex("faa_user_unique").on(table.proxyHostId, table.userId),
    groupUnique: uniqueIndex("faa_group_unique").on(table.proxyHostId, table.groupId),
  }),
);

export const forwardAuthSessions = sqliteTable(
  "forward_auth_sessions",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    proxyHostId: integer("proxyHostId")
      .references(() => proxyHosts.id, { onDelete: "cascade" })
      .notNull(),
    audienceOrigin: text("audienceOrigin").notNull(),
    tokenHash: text("tokenHash").notNull(),
    expiresAt: text("expiresAt").notNull(),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    tokenHashUnique: uniqueIndex("fas_token_hash_unique").on(table.tokenHash),
    userIdx: index("fas_user_idx").on(table.userId),
    proxyHostIdx: index("fas_proxy_host_idx").on(table.proxyHostId),
    expiresIdx: index("fas_expires_idx").on(table.expiresAt),
  }),
);

export const forwardAuthExchanges = sqliteTable(
  "forward_auth_exchanges",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    sessionId: integer("sessionId")
      .references(() => forwardAuthSessions.id, { onDelete: "cascade" })
      .notNull(),
    proxyHostId: integer("proxyHostId")
      .references(() => proxyHosts.id, { onDelete: "cascade" })
      .notNull(),
    audienceOrigin: text("audienceOrigin").notNull(),
    codeHash: text("codeHash").notNull(),
    // Legacy compatibility column. Only a fixed placeholder is stored; the
    // replacement session token is generated at atomic redemption time.
    sessionToken: text("sessionToken").notNull(),
    redirectUri: text("redirectUri").notNull(),
    expiresAt: text("expiresAt").notNull(),
    used: integer("used", { mode: "boolean" }).notNull().default(false),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    codeHashUnique: uniqueIndex("fae_code_hash_unique").on(table.codeHash),
  }),
);

export const forwardAuthRedirectIntents = sqliteTable(
  "forward_auth_redirect_intents",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    ridHash: text("ridHash").notNull(),
    proxyHostId: integer("proxyHostId")
      .references(() => proxyHosts.id, { onDelete: "cascade" })
      .notNull(),
    audienceOrigin: text("audienceOrigin").notNull(),
    redirectUri: text("redirectUri").notNull(),
    expiresAt: text("expiresAt").notNull(),
    consumed: integer("consumed", { mode: "boolean" }).notNull().default(false),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    ridHashUnique: uniqueIndex("fari_rid_hash_unique").on(table.ridHash),
    expiresIdx: index("fari_expires_idx").on(table.expiresAt),
  }),
);

// ── L4 Proxy Hosts ───────────────────────────────────────────────────

export const l4ProxyHosts = sqliteTable("l4_proxy_hosts", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  protocol: text("protocol").notNull(),
  listenAddress: text("listenAddress").notNull(),
  upstreams: text("upstreams").notNull(),
  matcherType: text("matcherType").notNull().default("none"),
  matcherValue: text("matcherValue"),
  tlsTermination: integer("tlsTermination", { mode: "boolean" }).notNull().default(false),
  proxyProtocolVersion: text("proxyProtocolVersion"),
  proxyProtocolReceive: integer("proxyProtocolReceive", { mode: "boolean" })
    .notNull()
    .default(false),
  ownerUserId: integer("ownerUserId").references(() => users.id, { onDelete: "set null" }),
  meta: text("meta"),
  enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
  createdAt: text("createdAt").notNull(),
  updatedAt: text("updatedAt").notNull(),
});

/**
 * Which agents serve a host.
 *
 * No rows for a host means every agent serves it, which is what the whole fleet did before this
 * table existed - so an upgrade changes nothing and an operator opts in per host. Many-to-many
 * rather than a column, because two edge nodes serving one host is an ordinary HA arrangement and
 * a single-valued assignment would forbid what the fleet-wide broadcast already allowed.
 */
export const proxyHostAgents = sqliteTable(
  "proxy_host_agents",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    proxyHostId: integer("proxyHostId")
      .references(() => proxyHosts.id, { onDelete: "cascade" })
      .notNull(),
    agentId: integer("agentId")
      .references(() => agents.id, { onDelete: "cascade" })
      .notNull(),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    pairUnique: uniqueIndex("proxy_host_agents_unique").on(table.proxyHostId, table.agentId),
    agentIdx: index("proxy_host_agents_agent_idx").on(table.agentId),
  }),
);

/** The same, for layer-4 hosts. Separate table because the two host tables are separate. */
export const l4ProxyHostAgents = sqliteTable(
  "l4_proxy_host_agents",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    l4ProxyHostId: integer("l4ProxyHostId")
      .references(() => l4ProxyHosts.id, { onDelete: "cascade" })
      .notNull(),
    agentId: integer("agentId")
      .references(() => agents.id, { onDelete: "cascade" })
      .notNull(),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    pairUnique: uniqueIndex("l4_proxy_host_agents_unique").on(table.l4ProxyHostId, table.agentId),
    agentIdx: index("l4_proxy_host_agents_agent_idx").on(table.agentId),
  }),
);

/**
 * IdP group names that resolve to a CPM group.
 *
 * The prefix convention on `oauth_providers` mirrors claimed groups by name, which works right up
 * until the IdP's name is not the one an operator wants to see - "AD-Infra-Proxy-Admins" against a
 * CPM group called "Networking". This table is that mapping written down: a CPM group can claim as
 * many external names as it likes, and the prefix convention keeps working for everything not
 * named here.
 *
 * `providerId` is nullable and means "any provider", for the deployment with one IdP that does not
 * want to restate it. Uniqueness is enforced in the model rather than by an index, because
 * PostgreSQL treats NULLs as distinct and a partial index per case would be two indexes saying one
 * thing.
 */
export const groupIdpMappings = sqliteTable(
  "group_idp_mappings",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    groupId: integer("groupId")
      .references(() => groups.id, { onDelete: "cascade" })
      .notNull(),
    providerId: text("providerId").references(() => oauthProviders.id, { onDelete: "cascade" }),
    /** As the operator typed it, for display. */
    externalName: text("externalName").notNull(),
    /** Lower-cased and path-stripped, which is what claims are compared against. */
    externalKey: text("externalKey").notNull(),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    groupIdx: index("group_idp_mappings_group_idx").on(table.groupId),
    keyIdx: index("group_idp_mappings_key_idx").on(table.externalKey),
  }),
);

/**
 * What a group is allowed to manage.
 *
 * Additive, never subtractive: a grant widens what an `operator` can reach and does nothing at all
 * to an `admin`, a `user` or a `viewer`. That is what makes this safe to ship - no existing user's
 * access changes until someone is deliberately moved to the operator role.
 *
 * One nullable column per resource kind rather than a polymorphic (type, id) pair, matching
 * `forward_auth_access`: it buys real foreign keys, so deleting a host takes its grants with it
 * instead of leaving a row pointing at an id something else will later reuse.
 */
export const groupGrants = sqliteTable(
  "group_grants",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    groupId: integer("groupId")
      .references(() => groups.id, { onDelete: "cascade" })
      .notNull(),
    proxyHostId: integer("proxyHostId").references(() => proxyHosts.id, { onDelete: "cascade" }),
    l4ProxyHostId: integer("l4ProxyHostId").references(() => l4ProxyHosts.id, {
      onDelete: "cascade",
    }),
    agentId: integer("agentId").references(() => agents.id, { onDelete: "cascade" }),
    /** "view" or "manage". A manage grant implies view. */
    capability: text("capability").notNull().default("manage"),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    groupIdx: index("group_grants_group_idx").on(table.groupId),
    proxyHostUnique: uniqueIndex("group_grants_proxy_host_unique").on(
      table.groupId,
      table.proxyHostId,
    ),
    l4HostUnique: uniqueIndex("group_grants_l4_host_unique").on(table.groupId, table.l4ProxyHostId),
    agentUnique: uniqueIndex("group_grants_agent_unique").on(table.groupId, table.agentId),
  }),
);
