/**
 * Drizzle has no dialect-neutral builder and the dialect is a runtime value, so SQLite tables are
 * exported typed as their PostgreSQL twins (db-schema-parity.test.ts). Decided from the
 * environment, not the connection, so tests can import tables without opening a database.
 */
import { databaseDialect } from "./dialect";
import * as pgSchema from "./schema.pg";
import * as sqliteSchema from "./schema.sqlite";

export const schemaDialect = databaseDialect(process.env);

// Spread into a plain object: a module namespace has a null prototype, and Better Auth's schema
// check (drizzle's `is()`) throws on one under Vite, failing every sign-in with a 500.
export const activeSchema = {
  ...(schemaDialect === "sqlite" ? sqliteSchema : pgSchema),
} as unknown as typeof pgSchema;

export const {
  users,
  sessions,
  accounts,
  verifications,
  twoFactors,
  passkeys,
  accessListIpRules,
  accessListDnsCache,
  oauthProviders,
  ssoProviders,
  settings,
  settingsStaged,
  settingsRevisions,
  agents,
  accessLists,
  accessListEntries,
  certificates,
  caCertificates,
  issuedClientCertificates,
  proxyHosts,
  apiTokens,
  auditEvents,
  auditChain,
  mtlsRoles,
  mtlsCertificateRoles,
  mtlsAccessRules,
  groups,
  groupMembers,
  forwardAuthAccess,
  forwardAuthSessions,
  forwardAuthExchanges,
  forwardAuthRedirectIntents,
  l4ProxyHosts,
  proxyHostAgents,
  l4ProxyHostAgents,
  groupIdpMappings,
  groupGrants,
  roles,
  roleMappings,
  scimConnections,
  scimRoleMappings,
  scimConnectionBindings,
  scimIdentityTombstones,
  scimSubjects,
  scimUsers,
  scimProjectionGrants,
  scimGroups,
  scimGroupMembers,
  pushSubscriptions,
  analyticsViews,
  controllerReplicas,
  clusterGenerations,
  rateLimitCounters,
  spentNonces,
  agentPairingSecrets,
  agentConnections,
  agentOutbox,
  agentCommandResults,
  upstreamErrorCounts,
  geoipDatabases,
  wafPresets,
  crsPlugins,
  wafExclusions,
  wafEventReviews,
  blockedSources,
  backupDestinations,
  backupSchedules,
  backupRuns,
  hostRevisions,
  notificationChannels,
  alertRules,
  alertKeys,
  alertEvents,
  alertDeliveries,
  alertDigests,
  alertDigestRuns,
  auditSinks,
  auditSecurityRecords,
  auditSecurityHead,
  accessReviewCampaigns,
  accessReviewItems,
  changeRequests,
  changeRequestDecisions,
} = activeSchema;
