// Code generated by scripts/generate-sqlite-schema.ts. DO NOT EDIT.
// Edit src/lib/db/schema.pg.ts and re-run `bun scripts/generate-sqlite-schema.ts`.
import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
import { uuidv7 } from "./uuidv7";
import { binary, isoTimestamp } from "./columns.sqlite";

export const users = sqliteTable(
  "users",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    email: text("email").notNull(),
    name: text("name"),
    passwordHash: text("passwordHash"),
    // Null without a password or for one predating this column. Not the credential account's
    // updatedAt: the env-seeded admin rewrites that row on every start.
    passwordChangedAt: isoTimestamp("passwordChangedAt"),
    role: text("role").notNull().default("user"),
    provider: text("provider"),
    subject: text("subject"),
    avatarUrl: text("avatarUrl"),
    status: text("status").notNull().default("active"),
    username: text("username"),
    displayUsername: text("displayUsername"),
    emailVerified: integer("emailVerified", { mode: "boolean" }).notNull().default(false),
    // Set by Better Auth's two-factor plugin once TOTP is verified; local accounts only.
    twoFactorEnabled: integer("twoFactorEnabled", { mode: "boolean" }).notNull().default(false),
    // Forward auth's opaque user id. Nullable: rows from raw SQL are filled by `ensureUserUuids`.
    uuid: text("uuid").$defaultFn(() => uuidv7()),
    // Written when a sign-in completes (lib/auth/last-sign-in.ts); null until the first one.
    lastSignInAt: isoTimestamp("lastSignInAt"),
    lastSignInMethod: text("lastSignInMethod"),
    // Display preferences that follow the account; null falls back to the browser's.
    timeZone: text("timeZone"),
    numberFormat: text("numberFormat"),
    createdAt: isoTimestamp("createdAt").notNull(),
    updatedAt: isoTimestamp("updatedAt").notNull(),
  },
  (table) => ({
    emailUnique: uniqueIndex("users_email_unique").on(table.email),
    uuidUnique: uniqueIndex("users_uuid_unique").on(table.uuid),
  }),
);

// Auth tables use camelCase DB columns to match Better Auth's Kysely adapter.
export const sessions = sqliteTable(
  "sessions",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    token: text("token").notNull(),
    expiresAt: isoTimestamp("expiresAt").notNull(),
    ipAddress: text("ipAddress"),
    userAgent: text("userAgent"),
    // For OIDC back-channel logout. `sid` is unique only per issuer, hence the provider beside it.
    oidcProviderId: text("oidcProviderId"),
    oidcSid: text("oidcSid"),
    // An admin's "view as" preview; narrows this session only. Groups are a JSON array of ids.
    viewAsRole: text("viewAsRole"),
    viewAsGroupIds: text("viewAsGroupIds"),
    viewAsExpiresAt: isoTimestamp("viewAsExpiresAt"),
    createdAt: isoTimestamp("createdAt").notNull(),
    updatedAt: isoTimestamp("updatedAt").notNull(),
  },
  (table) => ({
    tokenUnique: uniqueIndex("sessions_token_unique").on(table.token),
    userIdx: index("sessions_user_idx").on(table.userId),
    oidcSessionIdx: index("sessions_oidc_session_idx").on(table.oidcProviderId, table.oidcSid),
    // The hourly sweep of expired sessions (lib/security/housekeeping).
    expiresIdx: index("sessions_expires_idx").on(table.expiresAt),
  }),
);

export const accounts = sqliteTable(
  "accounts",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    accountId: text("accountId").notNull(),
    providerId: text("providerId").notNull(),
    accessToken: text("accessToken"),
    refreshToken: text("refreshToken"),
    idToken: text("idToken"),
    accessTokenExpiresAt: isoTimestamp("accessTokenExpiresAt"),
    refreshTokenExpiresAt: isoTimestamp("refreshTokenExpiresAt"),
    scope: text("scope"),
    password: text("password"),
    createdAt: isoTimestamp("createdAt").notNull(),
    updatedAt: isoTimestamp("updatedAt").notNull(),
  },
  (table) => ({
    providerAccountIdx: uniqueIndex("accounts_provider_account_idx").on(
      table.providerId,
      table.accountId,
    ),
    userIdx: index("accounts_user_idx").on(table.userId),
  }),
);

export const verifications = sqliteTable("verifications", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: isoTimestamp("expiresAt").notNull(),
  createdAt: isoTimestamp("createdAt"),
  updatedAt: isoTimestamp("updatedAt"),
});

// Better Auth's `twoFactor` model. `secret` and `backupCodes` are encrypted by the plugin with the
// auth secret; the lockout columns cap consecutive wrong codes per account.
export const twoFactors = sqliteTable(
  "two_factors",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    secret: text("secret").notNull(),
    backupCodes: text("backupCodes").notNull(),
    verified: integer("verified", { mode: "boolean" }).notNull().default(true),
    failedVerificationCount: integer("failedVerificationCount").notNull().default(0),
    lockedUntil: isoTimestamp("lockedUntil"),
  },
  (table) => ({
    userUnique: uniqueIndex("two_factors_user_unique").on(table.userId),
  }),
);

// Better Auth's `passkey` model (@better-auth/passkey). `publicKey` is a COSE key, not a secret;
// `transports` is comma-separated. A credential is bound to the rpID it was made on, the Public
// URL's hostname, so changing that hostname orphans every row here.
export const passkeys = sqliteTable(
  "passkeys",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name"),
    publicKey: text("publicKey").notNull(),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    credentialID: text("credentialID").notNull(),
    counter: integer("counter").notNull(),
    deviceType: text("deviceType").notNull(),
    backedUp: integer("backedUp", { mode: "boolean" }).notNull(),
    transports: text("transports"),
    aaguid: text("aaguid"),
    createdAt: isoTimestamp("createdAt"),
  },
  (table) => ({
    credentialUnique: uniqueIndex("passkeys_credential_unique").on(table.credentialID),
    userIdx: index("passkeys_user_idx").on(table.userId),
  }),
);

export const oauthProviders = sqliteTable(
  "oauth_providers",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    type: text("type").notNull().default("oidc"),
    clientId: text("clientId").notNull(),
    clientSecret: text("clientSecret").notNull(),
    issuer: text("issuer"),
    authorizationUrl: text("authorizationUrl"),
    tokenUrl: text("tokenUrl"),
    userinfoUrl: text("userinfoUrl"),
    scopes: text("scopes").notNull().default("openid email profile"),
    autoLink: integer("autoLink", { mode: "boolean" }).notNull().default(false),
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    source: text("source").notNull().default("ui"),
    // ── OIDC group mapping ────────────────────────────────────────────────
    // Claim holding the user's groups. Dot-separated paths address nested claims (e.g.
    // "resource_access.cpm.roles").
    groupsClaim: text("groupsClaim").notNull().default("groups"),
    // OIDC only: a claim of its own for role mapping. Null reads roles from `groupsClaim`.
    rolesClaim: text("rolesClaim"),
    // Convention prefix: with "CPM_", membership of "CPM_Admin" grants admin.
    groupPrefix: text("groupPrefix"),
    roleMappingEnabled: integer("roleMappingEnabled", { mode: "boolean" }).notNull().default(false),
    // Which groups give which role are `role_mappings` rows. Role assigned when none matched.
    defaultRole: text("defaultRole").notNull().default("user"),
    // Mirror the remaining prefixed IdP groups into CPM groups.
    syncGroups: integer("syncGroups", { mode: "boolean" }).notNull().default(false),
    // type='ldap' only (lib/ldap/config.ts); such a row borrows issuer, clientId and clientSecret.
    ldapConfig: text("ldapConfig"),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    nameUnique: uniqueIndex("oauth_providers_name_unique").on(table.name),
  }),
);

// Better Auth's `ssoProvider` model (@better-auth/sso), SAML only. CPM's half of each provider -
// name, switch, group mapping - is its `oauth_providers` row (type 'saml'), which `providerId`
// names. `samlConfig` is the plugin's JSON: IdP metadata and certificates, nothing secret.
export const ssoProviders = sqliteTable(
  "sso_providers",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    /** The service provider's entity ID, which assertions must name as their audience. */
    issuer: text("issuer").notNull(),
    oidcConfig: text("oidcConfig"),
    samlConfig: text("samlConfig"),
    userId: integer("userId").references(() => users.id, { onDelete: "set null" }),
    providerId: text("providerId")
      .references(() => oauthProviders.id, { onDelete: "cascade" })
      .notNull(),
    organizationId: text("organizationId"),
    /** Email domains whose first sign-in may join an existing account with the same email. */
    domain: text("domain").notNull().default(""),
    // Domain verification is how the plugin trusts `domain`; CPM's administrators vouch instead.
    domainVerified: integer("domainVerified", { mode: "boolean" }).notNull().default(true),
  },
  (table) => ({
    providerUnique: uniqueIndex("sso_providers_provider_unique").on(table.providerId),
  }),
);

export const settings = sqliteTable("settings", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  updatedAt: text("updatedAt").notNull(),
});

/**
 * Settings edited but not yet applied. Same shape as `settings`, so a staged row is a drop-in;
 * per user so one admin's apply never lands another's half-finished edits.
 */
export const settingsStaged = sqliteTable(
  "settings_staged",
  {
    key: text("key").notNull(),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    value: text("value").notNull(),
    stagedAt: text("stagedAt").notNull(),
  },
  (table) => ({
    pk: uniqueIndex("settings_staged_user_key_idx").on(table.userId, table.key),
  }),
);

/**
 * One row per apply. `summary` is rendered at apply time, since re-reading current values later
 * would narrate the present. `changes` (before/after JSON) is null on rows predating it.
 */
export const settingsRevisions = sqliteTable("settings_revisions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  appliedBy: integer("appliedBy").references(() => users.id, { onDelete: "set null" }),
  appliedByName: text("appliedByName"),
  summary: text("summary").notNull(),
  keys: text("keys").notNull(),
  changes: text("changes"),
  outcome: text("outcome").notNull(),
  error: text("error"),
  appliedAt: text("appliedAt").notNull(),
});

/**
 * Paired agents. No address: agents dial in, so reachability lives in `lib/agent/registry.ts`.
 * Pairing upserts on `agentId`, so a re-pair replaces the row.
 */
export const agents = sqliteTable(
  "agents",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    agentId: text("agentId").notNull(),
    /** Encrypted at rest. */
    secret: text("secret").notNull(),
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    /** JSON, or null to keep tracking the fleet default rather than a stale copy of it. */
    buildSettings: text("buildSettings"),
    lastSeenAt: text("lastSeenAt"),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    agentIdUnique: uniqueIndex("agents_agentId_unique").on(table.agentId),
  }),
);

export const accessLists = sqliteTable("access_lists", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  description: text("description"),
  // What a request matching none of the IP rules gets; only consulted while there are rules.
  ipDefault: text("ipDefault").notNull().default("deny"),
  // "all": pass the IP rules and the password. "any": either will do.
  satisfy: text("satisfy").notNull().default("all"),
  // Forward the basic-auth Authorization header to the upstream.
  passAuth: integer("passAuth", { mode: "boolean" }).notNull().default(false),
  // What a denied request gets: null keeps 403. A redirect URL wins over the status and body.
  denyStatus: integer("denyStatus"),
  denyBody: text("denyBody"),
  denyRedirectUrl: text("denyRedirectUrl"),
  // Deny when the client address cannot be told apart from a trusted proxy's.
  failClosed: integer("failClosed", { mode: "boolean" }).notNull().default(false),
  createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
  createdAt: text("createdAt").notNull(),
  updatedAt: text("updatedAt").notNull(),
});

export const accessListEntries = sqliteTable(
  "access_list_entries",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    accessListId: integer("accessListId")
      .references(() => accessLists.id, { onDelete: "cascade" })
      .notNull(),
    username: text("username").notNull(),
    passwordHash: text("passwordHash").notNull(),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    accessListIdIdx: index("access_list_entries_list_idx").on(table.accessListId),
  }),
);

/** Ordered allow/deny rules on the client; the first that matches decides. */
export const accessListIpRules = sqliteTable(
  "access_list_ip_rules",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    accessListId: integer("accessListId")
      .references(() => accessLists.id, { onDelete: "cascade" })
      .notNull(),
    action: text("action").notNull(),
    // Exactly one target. A hostname may end in /N, the IPv6 prefix its AAAA answers widen to.
    cidr: text("cidr"),
    hostname: text("hostname"),
    country: text("country"),
    continent: text("continent"),
    // Up to 2^32 - 1, past a PostgreSQL integer.
    asn: integer("asn"),
    note: text("note"),
    // Past it the rule is left out of the config, then deleted.
    expiresAt: text("expiresAt"),
    sortOrder: integer("sortOrder").notNull(),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    accessListIdIdx: index("access_list_ip_rules_list_idx").on(table.accessListId),
    // The expiry prune's scan; partial, since most rules never expire.
    expiresAtIdx: index("access_list_ip_rules_expires_at_idx")
      .on(table.expiresAt)
      .where(sql`"expiresAt" IS NOT NULL`),
  }),
);

/**
 * What the hostnames in IP rules last resolved to, so a restart keeps the last known set. A cache:
 * never backed up, and rebuilt by the refresher (lib/access-lists/dns.ts).
 */
export const accessListDnsCache = sqliteTable("access_list_dns_cache", {
  hostname: text("hostname").primaryKey(),
  // JSON array of addresses; empty until a lookup succeeds, and again 24 h after the last one did.
  addresses: text("addresses").notNull(),
  resolvedAt: text("resolvedAt"),
  expiresAt: text("expiresAt").notNull(),
  lastError: text("lastError"),
  lastErrorAt: text("lastErrorAt"),
});

export const certificates = sqliteTable("certificates", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  type: text("type").notNull(),
  domainNames: text("domainNames").notNull(),
  autoRenew: integer("autoRenew", { mode: "boolean" }).notNull().default(true),
  providerOptions: text("providerOptions"),
  certificatePem: text("certificatePem"),
  privateKeyPem: text("privateKeyPem"),
  createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
  createdAt: text("createdAt").notNull(),
  updatedAt: text("updatedAt").notNull(),
  /** `upload`, or `agent-file`: read by `sourceAgentId` from paths in its CERT_FILES_HOST_DIR. */
  source: text("source").notNull().default("upload"),
  /** Null once that agent is deleted: the last PEM stays, but no agent serves it. */
  sourceAgentId: integer("sourceAgentId").references(() => agents.id, { onDelete: "set null" }),
  sourceCertPath: text("sourceCertPath"),
  sourceKeyPath: text("sourceKeyPath"),
  sourceReadAt: text("sourceReadAt"),
  /** A `CertificateFileError` code; the last good PEM keeps serving meanwhile. */
  sourceError: text("sourceError"),
});

export const caCertificates = sqliteTable("ca_certificates", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  certificatePem: text("certificatePem").notNull(),
  privateKeyPem: text("privateKeyPem"),
  createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
  createdAt: text("createdAt").notNull(),
  updatedAt: text("updatedAt").notNull(),
});

export const issuedClientCertificates = sqliteTable(
  "issued_client_certificates",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    caCertificateId: integer("caCertificateId")
      .references(() => caCertificates.id, { onDelete: "cascade" })
      .notNull(),
    commonName: text("commonName").notNull(),
    serialNumber: text("serialNumber").notNull(),
    fingerprintSha256: text("fingerprintSha256").notNull(),
    certificatePem: text("certificatePem").notNull(),
    validFrom: text("validFrom").notNull(),
    validTo: text("validTo").notNull(),
    revokedAt: text("revokedAt"),
    createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    caCertificateIdx: index("issued_client_certificates_ca_idx").on(table.caCertificateId),
    revokedAtIdx: index("issued_client_certificates_revoked_at_idx").on(table.revokedAt),
  }),
);

export const proxyHosts = sqliteTable(
  "proxy_hosts",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    description: text("description"),
    /** JSON array, normalised on save; labels for finding hosts, never read by the config build. */
    tags: text("tags").notNull().default("[]"),
    domains: text("domains").notNull(),
    upstreams: text("upstreams").notNull(),
    certificateId: integer("certificateId").references(() => certificates.id, {
      onDelete: "set null",
    }),
    accessListId: integer("accessListId").references(() => accessLists.id, {
      onDelete: "set null",
    }),
    ownerUserId: integer("ownerUserId").references(() => users.id, { onDelete: "set null" }),
    sslForced: integer("sslForced", { mode: "boolean" }).notNull().default(true),
    hstsEnabled: integer("hstsEnabled", { mode: "boolean" }).notNull().default(true),
    hstsSubdomains: integer("hstsSubdomains", { mode: "boolean" }).notNull().default(false),
    allowWebsocket: integer("allowWebsocket", { mode: "boolean" }).notNull().default(true),
    preserveHostHeader: integer("preserveHostHeader", { mode: "boolean" }).notNull().default(true),
    meta: text("meta"),
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
    skipHttpsHostnameValidation: integer("skipHttpsHostnameValidation", { mode: "boolean" })
      .notNull()
      .default(false),
    // The id in URLs and the REST API; the serial id stays the key every table points at.
    uuid: text("uuid").$defaultFn(() => uuidv7()),
  },
  (table) => ({
    uuidUnique: uniqueIndex("proxy_hosts_uuid_unique").on(table.uuid),
  }),
);

export const apiTokens = sqliteTable(
  "api_tokens",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    tokenHash: text("tokenHash").notNull(),
    createdBy: integer("createdBy")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    createdAt: text("createdAt").notNull(),
    lastUsedAt: text("lastUsedAt"),
    expiresAt: text("expiresAt"),
    // "full", "read" or "custom"; a custom scope's permissions are a JSON array (lib/api-tokens).
    scope: text("scope").notNull().default("full"),
    permissions: text("permissions"),
  },
  (table) => ({
    tokenHashUnique: uniqueIndex("api_tokens_token_hash_unique").on(table.tokenHash),
  }),
);

export const auditEvents = sqliteTable(
  "audit_events",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    userId: integer("userId").references(() => users.id, { onDelete: "set null" }),
    action: text("action").notNull(),
    entityType: text("entityType").notNull(),
    entityId: integer("entityId"),
    summary: text("summary"),
    data: text("data"),
    createdAt: text("createdAt").notNull(),
    // The hash chain (lib/audit/chain.ts); all null on events written before it existed.
    // actorId copies userId without the foreign key, which nulls it when the user is deleted.
    actorId: integer("actorId"),
    seq: integer("seq"),
    prevHash: text("prevHash"),
    hash: text("hash"),
  },
  // The Overview's newest-first list and its server-events line both range over this.
  (table) => ({
    createdAtIdx: index("audit_events_created_at_idx").on(table.createdAt),
    seqIdx: uniqueIndex("audit_events_seq_idx").on(table.seq),
    // The audit page's actor and action filters, newest first; without these each is a scan.
    userIdx: index("audit_events_user_idx").on(table.userId, table.createdAt),
    actionIdx: index("audit_events_action_idx").on(table.action, table.createdAt),
    // One entity's history, newest first: a host's page.
    entityIdx: index("audit_events_entity_idx").on(
      table.entityType,
      table.entityId,
      table.createdAt,
    ),
  }),
);

/** One row (id 1): the chain's head, locked by every chained insert, and where it starts. */
export const auditChain = sqliteTable("audit_chain", {
  id: integer("id").primaryKey(),
  headSeq: integer("headSeq").notNull(),
  headHash: text("headHash").notNull(),
  anchorSeq: integer("anchorSeq").notNull(),
  anchorHash: text("anchorHash").notNull(),
  // Events from before the chain, each carrying a keyed mark instead of a link.
  legacyCount: integer("legacyCount").notNull().default(0),
  // HMAC over the fields above; null only before the first keyed write (src/lib/audit/chain.ts).
  seal: text("seal"),
  updatedAt: text("updatedAt").notNull(),
});

// traffic_events and waf_events live in ClickHouse (src/lib/clickhouse/client.ts); their parsers
// and offsets live in the agent, which is where the Caddy log file is.

// ── mTLS RBAC ──────────────────────────────────────────────────────────

export const mtlsRoles = sqliteTable(
  "mtls_roles",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    description: text("description"),
    createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    nameUnique: uniqueIndex("mtls_roles_name_unique").on(table.name),
  }),
);

// Named SecLang snippets the global WAF and each host select by id (upstream #149).
export const wafPresets = sqliteTable(
  "waf_presets",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    description: text("description"),
    directives: text("directives").notNull(),
    createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    nameUnique: uniqueIndex("waf_presets_name_unique").on(table.name),
  }),
);

// CRS plugins installed from the plugin registry, pinned to the release they were fetched at. The
// rule files are stored rather than fetched per apply, so a config build never waits on GitHub.
export const crsPlugins = sqliteTable(
  "crs_plugins",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    repository: text("repository").notNull(),
    version: text("version").notNull(),
    description: text("description"),
    ruleIdStart: integer("ruleIdStart").notNull(),
    ruleIdEnd: integer("ruleIdEnd").notNull(),
    configRules: text("configRules").notNull(),
    beforeRules: text("beforeRules").notNull(),
    afterRules: text("afterRules").notNull(),
    // The operator's edit of the -config file; null runs the upstream one. Survives an update.
    configOverride: text("configOverride"),
    // JSON array of the plugins/ files the release had, for display; the rules are stored by kind.
    fileNames: text("fileNames").notNull().default("[]"),
    createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    nameUnique: uniqueIndex("crs_plugins_name_unique").on(table.name),
  }),
);

/** A WAF rule switched off globally or on one host, optionally under a path or for one variable. */
export const wafExclusions = sqliteTable(
  "waf_exclusions",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    ruleId: integer("ruleId").notNull(),
    /** Null is every host. */
    proxyHostId: integer("proxyHostId").references(() => proxyHosts.id, { onDelete: "cascade" }),
    /** The dashboard host, which has no `proxy_hosts` row for proxyHostId to name. */
    dashboard: integer("dashboard", { mode: "boolean" }).notNull().default(false),
    /** Decoded and normalised; a trailing `*` is a prefix. */
    path: text("path"),
    /** A rule target such as `ARGS:content`, which the rule then skips. */
    target: text("target"),
    reason: text("reason").notNull().default(""),
    createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    hostIdx: index("waf_exclusions_host_idx").on(table.proxyHostId),
  }),
);

/** A WAF event someone looked at. Events live in ClickHouse, so this keys them by content. */
export const wafEventReviews = sqliteTable(
  "waf_event_reviews",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    eventKey: text("eventKey").notNull(),
    /** `intended` or `false_positive`. */
    verdict: text("verdict").notNull(),
    userId: integer("userId").references(() => users.id, { onDelete: "set null" }),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    eventKeyUnique: uniqueIndex("waf_event_reviews_event_key_unique").on(table.eventKey),
  }),
);

/** The global deny list, checked before every other handler on HTTP hosts. */
export const blockedSources = sqliteTable(
  "blocked_sources",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    /** `ip`, `cidr`, `country`, `continent` or `asn`. */
    kind: text("kind").notNull(),
    value: text("value").notNull(),
    reason: text("reason").notNull().default(""),
    /** Null never expires. */
    expiresAt: text("expiresAt"),
    createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    kindValueUnique: uniqueIndex("blocked_sources_kind_value_unique").on(table.kind, table.value),
    expiresAtIdx: index("blocked_sources_expires_at_idx").on(table.expiresAt),
  }),
);

export const mtlsCertificateRoles = sqliteTable(
  "mtls_certificate_roles",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    issuedClientCertificateId: integer("issuedClientCertificateId")
      .references(() => issuedClientCertificates.id, { onDelete: "cascade" })
      .notNull(),
    mtlsRoleId: integer("mtlsRoleId")
      .references(() => mtlsRoles.id, { onDelete: "cascade" })
      .notNull(),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    certRoleUnique: uniqueIndex("mtls_cert_role_unique").on(
      table.issuedClientCertificateId,
      table.mtlsRoleId,
    ),
    roleIdx: index("mtls_certificate_roles_role_idx").on(table.mtlsRoleId),
  }),
);

export const mtlsAccessRules = sqliteTable(
  "mtls_access_rules",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    proxyHostId: integer("proxyHostId")
      .references(() => proxyHosts.id, { onDelete: "cascade" })
      .notNull(),
    pathPattern: text("pathPattern").notNull(),
    allowedRoleIds: text("allowedRoleIds").notNull().default("[]"),
    allowedCertIds: text("allowedCertIds").notNull().default("[]"),
    denyAll: integer("denyAll", { mode: "boolean" }).notNull().default(false),
    priority: integer("priority").notNull().default(0),
    description: text("description"),
    createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    proxyHostIdx: index("mtls_access_rules_proxy_host_idx").on(table.proxyHostId),
    hostPathUnique: uniqueIndex("mtls_access_rules_host_path_unique").on(
      table.proxyHostId,
      table.pathPattern,
    ),
  }),
);

// ── Forward Auth (IdP) ───────────────────────────────────────────────

export const groups = sqliteTable(
  "groups",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    description: text("description"),
    createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
    // "ui" for operator-managed groups, "oidc" for groups created by an IdP group sync, "scim" for
    // groups a SCIM connection owns. Only "oidc" group membership is reconciled on sign-in.
    source: text("source").notNull().default("ui"),
    /** A role key every member holds besides their own; never the built-in admin. */
    role: text("role"),
    /** For source "scim": the SCIM group (scim_groups.id) this one mirrors. */
    scimGroupId: text("scimGroupId"),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    nameUnique: uniqueIndex("groups_name_unique").on(table.name),
    scimGroupUnique: uniqueIndex("groups_scim_group_unique").on(table.scimGroupId),
  }),
);

export const groupMembers = sqliteTable(
  "group_members",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    groupId: integer("groupId")
      .references(() => groups.id, { onDelete: "cascade" })
      .notNull(),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    memberUnique: uniqueIndex("group_members_unique").on(table.groupId, table.userId),
    userIdx: index("group_members_user_idx").on(table.userId),
  }),
);

export const forwardAuthAccess = sqliteTable(
  "forward_auth_access",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    proxyHostId: integer("proxyHostId")
      .references(() => proxyHosts.id, { onDelete: "cascade" })
      .notNull(),
    userId: integer("userId").references(() => users.id, { onDelete: "cascade" }),
    groupId: integer("groupId").references(() => groups.id, { onDelete: "cascade" }),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    hostIdx: index("faa_host_idx").on(table.proxyHostId),
    userUnique: uniqueIndex("faa_user_unique").on(table.proxyHostId, table.userId),
    groupUnique: uniqueIndex("faa_group_unique").on(table.proxyHostId, table.groupId),
  }),
);

export const forwardAuthSessions = sqliteTable(
  "forward_auth_sessions",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    proxyHostId: integer("proxyHostId")
      .references(() => proxyHosts.id, { onDelete: "cascade" })
      .notNull(),
    audienceOrigin: text("audienceOrigin").notNull(),
    tokenHash: text("tokenHash").notNull(),
    expiresAt: text("expiresAt").notNull(),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    tokenHashUnique: uniqueIndex("fas_token_hash_unique").on(table.tokenHash),
    userIdx: index("fas_user_idx").on(table.userId),
    proxyHostIdx: index("fas_proxy_host_idx").on(table.proxyHostId),
    expiresIdx: index("fas_expires_idx").on(table.expiresAt),
  }),
);

export const forwardAuthExchanges = sqliteTable(
  "forward_auth_exchanges",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    sessionId: integer("sessionId")
      .references(() => forwardAuthSessions.id, { onDelete: "cascade" })
      .notNull(),
    proxyHostId: integer("proxyHostId")
      .references(() => proxyHosts.id, { onDelete: "cascade" })
      .notNull(),
    audienceOrigin: text("audienceOrigin").notNull(),
    codeHash: text("codeHash").notNull(),
    // Legacy column holding a fixed placeholder; the real token is minted at redemption.
    sessionToken: text("sessionToken").notNull(),
    redirectUri: text("redirectUri").notNull(),
    expiresAt: text("expiresAt").notNull(),
    used: integer("used", { mode: "boolean" }).notNull().default(false),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    codeHashUnique: uniqueIndex("fae_code_hash_unique").on(table.codeHash),
  }),
);

export const forwardAuthRedirectIntents = sqliteTable(
  "forward_auth_redirect_intents",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    ridHash: text("ridHash").notNull(),
    proxyHostId: integer("proxyHostId")
      .references(() => proxyHosts.id, { onDelete: "cascade" })
      .notNull(),
    audienceOrigin: text("audienceOrigin").notNull(),
    redirectUri: text("redirectUri").notNull(),
    expiresAt: text("expiresAt").notNull(),
    consumed: integer("consumed", { mode: "boolean" }).notNull().default(false),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    ridHashUnique: uniqueIndex("fari_rid_hash_unique").on(table.ridHash),
    expiresIdx: index("fari_expires_idx").on(table.expiresAt),
  }),
);

// ── L4 Proxy Hosts ───────────────────────────────────────────────────

export const l4ProxyHosts = sqliteTable(
  "l4_proxy_hosts",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    description: text("description"),
    /** As on proxy_hosts. */
    tags: text("tags").notNull().default("[]"),
    protocol: text("protocol").notNull(),
    listenAddress: text("listenAddress").notNull(),
    upstreams: text("upstreams").notNull(),
    matcherType: text("matcherType").notNull().default("none"),
    matcherValue: text("matcherValue"),
    tlsTermination: integer("tlsTermination", { mode: "boolean" }).notNull().default(false),
    proxyProtocolVersion: text("proxyProtocolVersion"),
    proxyProtocolReceive: integer("proxyProtocolReceive", { mode: "boolean" })
      .notNull()
      .default(false),
    /** Its IP rules only. Deleting a list a host uses is refused by the model, not this key. */
    accessListId: integer("accessListId").references(() => accessLists.id, {
      onDelete: "set null",
    }),
    ownerUserId: integer("ownerUserId").references(() => users.id, { onDelete: "set null" }),
    meta: text("meta"),
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
    // The id in URLs and the REST API; the serial id stays the key every table points at.
    uuid: text("uuid").$defaultFn(() => uuidv7()),
  },
  (table) => ({
    uuidUnique: uniqueIndex("l4_proxy_hosts_uuid_unique").on(table.uuid),
  }),
);

/**
 * Which agents serve a host; no rows means every agent, so upgrades change nothing. Many-to-many
 * because two edge nodes serving one host is ordinary HA.
 */
export const proxyHostAgents = sqliteTable(
  "proxy_host_agents",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    proxyHostId: integer("proxyHostId")
      .references(() => proxyHosts.id, { onDelete: "cascade" })
      .notNull(),
    agentId: integer("agentId")
      .references(() => agents.id, { onDelete: "cascade" })
      .notNull(),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    pairUnique: uniqueIndex("proxy_host_agents_unique").on(table.proxyHostId, table.agentId),
    agentIdx: index("proxy_host_agents_agent_idx").on(table.agentId),
  }),
);

/** The same, for layer-4 hosts. Separate table because the two host tables are separate. */
export const l4ProxyHostAgents = sqliteTable(
  "l4_proxy_host_agents",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    l4ProxyHostId: integer("l4ProxyHostId")
      .references(() => l4ProxyHosts.id, { onDelete: "cascade" })
      .notNull(),
    agentId: integer("agentId")
      .references(() => agents.id, { onDelete: "cascade" })
      .notNull(),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    pairUnique: uniqueIndex("l4_proxy_host_agents_unique").on(table.l4ProxyHostId, table.agentId),
    agentIdx: index("l4_proxy_host_agents_agent_idx").on(table.agentId),
  }),
);

/**
 * IdP group names mapped to a CPM group, for names the prefix convention cannot express. Null
 * `providerId` means any provider; uniqueness lives in the model since PostgreSQL treats NULLs
 * as distinct.
 */
export const groupIdpMappings = sqliteTable(
  "group_idp_mappings",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    groupId: integer("groupId")
      .references(() => groups.id, { onDelete: "cascade" })
      .notNull(),
    providerId: text("providerId").references(() => oauthProviders.id, { onDelete: "cascade" }),
    /** As the operator typed it, for display. */
    externalName: text("externalName").notNull(),
    /** Lower-cased and path-stripped, which is what claims are compared against. */
    externalKey: text("externalKey").notNull(),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    groupIdx: index("group_idp_mappings_group_idx").on(table.groupId),
    keyIdx: index("group_idp_mappings_key_idx").on(table.externalKey),
  }),
);

/**
 * Roles an administrator defines. The four built-in roles live in code (`lib/roles/built-in.ts`)
 * and are never stored, so what they mean cannot drift from the code that checks them. `key` is
 * what users, groups and mappings point at, and survives a rename.
 */
export const roles = sqliteTable(
  "roles",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    key: text("key").notNull(),
    name: text("name").notNull(),
    description: text("description"),
    /** A JSON array of capabilities, as `lib/roles/capabilities.ts` names them. */
    capabilities: text("capabilities").notNull().default("[]"),
    /** Hosts and agents only as far as the holder's groups are granted, as the built-in operator. */
    scoped: integer("scoped", { mode: "boolean" }).notNull().default(false),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    keyUnique: uniqueIndex("roles_key_unique").on(table.key),
  }),
);

/**
 * Which identity-provider groups give which role, per OIDC provider or LDAP directory: one row a
 * name, matched as `lib/auth/oidc/groups.ts` compares them. `role` is a role key.
 */
export const roleMappings = sqliteTable(
  "role_mappings",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    providerId: text("providerId")
      .references(() => oauthProviders.id, { onDelete: "cascade" })
      .notNull(),
    role: text("role").notNull(),
    externalName: text("externalName").notNull(),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    providerIdx: index("role_mappings_provider_idx").on(table.providerId),
    nameUnique: uniqueIndex("role_mappings_unique").on(
      table.providerId,
      table.role,
      table.externalName,
    ),
  }),
);

/**
 * An identity provider's SCIM provisioning credential (lib/scim). Separate from API tokens: it
 * reaches /api/scim/v2 only, and nothing else takes it.
 */
export const scimConnections = sqliteTable(
  "scim_connections",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    /** SHA-256 of the bearer token, which is shown once. */
    tokenHash: text("tokenHash").notNull(),
    /** The token's last characters, to tell two apart. */
    tokenHint: text("tokenHint").notNull(),
    /** An account that already has the email is taken over rather than refused. */
    linkExisting: integer("linkExisting", { mode: "boolean" }).notNull().default(true),
    createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
    lastUsedAt: text("lastUsedAt"),
    tokenRotatedAt: text("tokenRotatedAt"),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    nameUnique: uniqueIndex("scim_connections_name_unique").on(table.name),
    tokenHashUnique: uniqueIndex("scim_connections_token_hash_unique").on(table.tokenHash),
  }),
);

/** Which provisioned group names give a group which role, per connection, as role_mappings. */
export const scimRoleMappings = sqliteTable(
  "scim_role_mappings",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    connectionId: integer("connectionId")
      .references(() => scimConnections.id, { onDelete: "cascade" })
      .notNull(),
    role: text("role").notNull(),
    externalName: text("externalName").notNull(),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    connectionIdx: index("scim_role_mappings_connection_idx").on(table.connectionId),
    nameUnique: uniqueIndex("scim_role_mappings_unique").on(
      table.connectionId,
      table.role,
      table.externalName,
    ),
  }),
);

// The SCIM plugin's own tables (@better-auth/scim), field for field as its schema names them; the
// adapter reaches them under its model names (auth/server.ts). Used under PostgreSQL only.

export const scimConnectionBindings = sqliteTable(
  "scim_connection_bindings",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    connectionId: text("connectionId").notNull(),
    connectionKey: text("connectionKey").notNull(),
    provisioningDomainId: text("provisioningDomainId").notNull(),
    createdAt: isoTimestamp("createdAt").notNull(),
    decommissionedAt: isoTimestamp("decommissionedAt"),
    decommissionStatus: text("decommissionStatus").default("active").notNull(),
    decommissionCursorUserId: text("decommissionCursorUserId"),
    decommissionReconciledUserCount: integer("decommissionReconciledUserCount")
      .default(0)
      .notNull(),
    decommissionBatchCount: integer("decommissionBatchCount").default(0).notNull(),
    decommissionRevision: integer("decommissionRevision").default(0).notNull(),
    decommissionCompletedAt: isoTimestamp("decommissionCompletedAt"),
    decommissionLeaseId: text("decommissionLeaseId"),
    decommissionLeaseExpiresAt: isoTimestamp("decommissionLeaseExpiresAt"),
  },
  (table) => ({
    connectionIdIdx: index("scim_connection_bindings_connectionId_idx").on(table.connectionId),
    connectionKeyUnique: uniqueIndex("scim_connection_bindings_connectionKey_unique").on(
      table.connectionKey,
    ),
  }),
);

export const scimIdentityTombstones = sqliteTable(
  "scim_identity_tombstones",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    connectionId: text("connectionId").notNull(),
    provisioningDomainId: text("provisioningDomainId").notNull(),
    externalId: text("externalId").notNull(),
    externalIdKey: text("externalIdKey").notNull(),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    profile: text("profile").notNull(),
    deletedAt: isoTimestamp("deletedAt").notNull(),
  },
  (table) => ({
    connectionIdIdx: index("scim_identity_tombstones_connectionId_idx").on(table.connectionId),
    provisioningDomainIdIdx: index("scim_identity_tombstones_provisioningDomainId_idx").on(
      table.provisioningDomainId,
    ),
    externalIdKeyUnique: uniqueIndex("scim_identity_tombstones_externalIdKey_unique").on(
      table.externalIdKey,
    ),
    userIdIdx: index("scim_identity_tombstones_userId_idx").on(table.userId),
  }),
);

export const scimSubjects = sqliteTable(
  "scim_subjects",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    profileSourceId: text("profileSourceId"),
    revision: integer("revision").notNull(),
    createdAt: isoTimestamp("createdAt").notNull(),
    updatedAt: isoTimestamp("updatedAt").notNull(),
  },
  (table) => ({
    userIdUnique: uniqueIndex("scim_subjects_userId_unique").on(table.userId),
    profileSourceIdIdx: index("scim_subjects_profileSourceId_idx").on(table.profileSourceId),
  }),
);

export const scimUsers = sqliteTable(
  "scim_users",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    connectionId: text("connectionId").notNull(),
    provisioningDomainId: text("provisioningDomainId").notNull(),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    connectionUserKey: text("connectionUserKey").notNull(),
    userName: text("userName").notNull(),
    userNameKey: text("userNameKey").notNull(),
    primaryEmail: text("primaryEmail").notNull(),
    workEmailValueIndex: text("workEmailValueIndex").notNull(),
    emailValueIndex: text("emailValueIndex").notNull(),
    displayName: text("displayName").notNull(),
    formattedName: text("formattedName").notNull(),
    givenName: text("givenName"),
    familyName: text("familyName"),
    serializedEmails: text("serializedEmails").notNull(),
    serializedAttributes: text("serializedAttributes"),
    externalId: text("externalId"),
    externalIdKey: text("externalIdKey"),
    active: integer("active", { mode: "boolean" }).notNull(),
    orderKey: text("orderKey").notNull(),
    createdAt: isoTimestamp("createdAt").notNull(),
    updatedAt: isoTimestamp("updatedAt").notNull(),
  },
  (table) => ({
    connectionIdIdx: index("scim_users_connectionId_idx").on(table.connectionId),
    provisioningDomainIdIdx: index("scim_users_provisioningDomainId_idx").on(
      table.provisioningDomainId,
    ),
    userIdIdx: index("scim_users_userId_idx").on(table.userId),
    connectionUserKeyUnique: uniqueIndex("scim_users_connectionUserKey_unique").on(
      table.connectionUserKey,
    ),
    userNameKeyUnique: uniqueIndex("scim_users_userNameKey_unique").on(table.userNameKey),
    externalIdKeyUnique: uniqueIndex("scim_users_externalIdKey_unique").on(table.externalIdKey),
    orderKeyUnique: uniqueIndex("scim_users_orderKey_unique").on(table.orderKey),
  }),
);

export const scimProjectionGrants = sqliteTable(
  "scim_projection_grants",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    connectionId: text("connectionId").notNull(),
    provisioningDomainId: text("provisioningDomainId").notNull(),
    scimUserId: integer("scimUserId")
      .references(() => scimUsers.id, { onDelete: "cascade" })
      .notNull(),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    sourceKind: text("sourceKind").notNull(),
    sourceId: text("sourceId").notNull(),
    sourceValue: text("sourceValue"),
    role: text("role").notNull(),
    grantKey: text("grantKey").notNull(),
    createdAt: isoTimestamp("createdAt").notNull(),
    updatedAt: isoTimestamp("updatedAt").notNull(),
  },
  (table) => ({
    connectionIdIdx: index("scim_projection_grants_connectionId_idx").on(table.connectionId),
    provisioningDomainIdIdx: index("scim_projection_grants_provisioningDomainId_idx").on(
      table.provisioningDomainId,
    ),
    scimUserIdIdx: index("scim_projection_grants_scimUserId_idx").on(table.scimUserId),
    userIdIdx: index("scim_projection_grants_userId_idx").on(table.userId),
    grantKeyUnique: uniqueIndex("scim_projection_grants_grantKey_unique").on(table.grantKey),
  }),
);

export const scimGroups = sqliteTable(
  "scim_groups",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    connectionId: text("connectionId").notNull(),
    provisioningDomainId: text("provisioningDomainId").notNull(),
    revision: integer("revision").default(0).notNull(),
    displayName: text("displayName").notNull(),
    displayNameKey: text("displayNameKey").notNull(),
    externalId: text("externalId"),
    externalIdKey: text("externalIdKey"),
    orderKey: text("orderKey").notNull(),
    createdAt: isoTimestamp("createdAt").notNull(),
    updatedAt: isoTimestamp("updatedAt").notNull(),
  },
  (table) => ({
    connectionIdIdx: index("scim_groups_connectionId_idx").on(table.connectionId),
    provisioningDomainIdIdx: index("scim_groups_provisioningDomainId_idx").on(
      table.provisioningDomainId,
    ),
    displayNameKeyUnique: uniqueIndex("scim_groups_displayNameKey_unique").on(table.displayNameKey),
    externalIdKeyUnique: uniqueIndex("scim_groups_externalIdKey_unique").on(table.externalIdKey),
    orderKeyUnique: uniqueIndex("scim_groups_orderKey_unique").on(table.orderKey),
  }),
);

export const scimGroupMembers = sqliteTable(
  "scim_group_members",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    connectionId: text("connectionId").notNull(),
    groupId: integer("groupId")
      .references(() => scimGroups.id, { onDelete: "cascade" })
      .notNull(),
    scimUserId: integer("scimUserId")
      .references(() => scimUsers.id, { onDelete: "cascade" })
      .notNull(),
    membershipKey: text("membershipKey").notNull(),
    createdAt: isoTimestamp("createdAt").notNull(),
  },
  (table) => ({
    connectionIdIdx: index("scim_group_members_connectionId_idx").on(table.connectionId),
    groupIdIdx: index("scim_group_members_groupId_idx").on(table.groupId),
    scimUserIdIdx: index("scim_group_members_scimUserId_idx").on(table.scimUserId),
    membershipKeyUnique: uniqueIndex("scim_group_members_membershipKey_unique").on(
      table.membershipKey,
    ),
  }),
);

/**
 * What a group may manage. Additive, and only for scoped roles such as `operator`. One nullable
 * column per resource kind, not a polymorphic pair, so real foreign keys delete grants with their
 * host.
 */
export const groupGrants = sqliteTable(
  "group_grants",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    groupId: integer("groupId")
      .references(() => groups.id, { onDelete: "cascade" })
      .notNull(),
    proxyHostId: integer("proxyHostId").references(() => proxyHosts.id, { onDelete: "cascade" }),
    l4ProxyHostId: integer("l4ProxyHostId").references(() => l4ProxyHosts.id, {
      onDelete: "cascade",
    }),
    agentId: integer("agentId").references(() => agents.id, { onDelete: "cascade" }),
    /** "view" or "manage". A manage grant implies view. */
    capability: text("capability").notNull().default("manage"),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    groupIdx: index("group_grants_group_idx").on(table.groupId),
    proxyHostUnique: uniqueIndex("group_grants_proxy_host_unique").on(
      table.groupId,
      table.proxyHostId,
    ),
    l4HostUnique: uniqueIndex("group_grants_l4_host_unique").on(table.groupId, table.l4ProxyHostId),
    agentUnique: uniqueIndex("group_grants_agent_unique").on(table.groupId, table.agentId),
  }),
);

/** A browser an administrator turned notifications on in. The keys encrypt each push for it. */
export const pushSubscriptions = sqliteTable(
  "push_subscriptions",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    /** The push service's URL for this browser; what the browser itself identifies it by. */
    endpoint: text("endpoint").notNull(),
    p256dh: text("p256dh").notNull(),
    auth: text("auth").notNull(),
    /** The reader's locale when they subscribed; a push has no request to negotiate one from. */
    locale: text("locale"),
    userAgent: text("userAgent"),
    /**
     * The session that turned it on. Not a foreign key: a session expiring must not stop pushes,
     * but revoking sessions (sign out others, a password change) takes their browsers with them.
     */
    sessionId: integer("sessionId"),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    endpointUnique: uniqueIndex("push_subscriptions_endpoint_unique").on(table.endpoint),
    userIdx: index("push_subscriptions_user_idx").on(table.userId),
  }),
);

/** A named analytics page state. Shared ones are listed for everyone who can open analytics. */
export const analyticsViews = sqliteTable(
  "analytics_views",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    userId: integer("userId")
      .references(() => users.id, { onDelete: "cascade" })
      .notNull(),
    name: text("name").notNull(),
    /** The page's query string, re-parsed on load, so an old view never bypasses sanitising. */
    query: text("query").notNull(),
    shared: integer("shared", { mode: "boolean" }).notNull().default(false),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    userIdx: index("analytics_views_user_idx").on(table.userId),
  }),
);

// ── Cluster ──────────────────────────────────────────────────────────

/** One row per running controller (lib/cluster); a crashed one's row lingers until pruned. */
export const controllerReplicas = sqliteTable("controller_replicas", {
  id: text("id").primaryKey(),
  hostname: text("hostname").notNull(),
  /** Of the key SESSION_SECRET derives: replicas disagreeing would each break the other's secrets. */
  keyFingerprint: text("keyFingerprint").notNull(),
  startedAt: integer("startedAt").notNull(),
  heartbeatAt: integer("heartbeatAt").notNull(),
});

/** Bumped per cache a write invalidates, so a replica that missed the NOTIFY still catches up. */
export const clusterGenerations = sqliteTable("cluster_generations", {
  name: text("name").primaryKey(),
  generation: integer("generation").notNull(),
});

/** Guess limits every replica must share (auth/rate-limit.ts); flood budgets stay in memory. */
export const rateLimitCounters = sqliteTable(
  "rate_limit_counters",
  {
    key: text("key").primaryKey(),
    count: integer("count").notNull(),
    /** Epoch ms; the count is forgotten from then. */
    resetAt: integer("resetAt").notNull(),
    blockedUntil: integer("blockedUntil"),
  },
  (table) => ({
    resetAtIdx: index("rate_limit_counters_reset_at_idx").on(table.resetAt),
  }),
);

/** Single-use values (request nonces, CAPTCHA passes, logout jtis) until they could verify no more. */
export const spentNonces = sqliteTable(
  "spent_nonces",
  {
    key: text("key").primaryKey(),
    expiresAt: integer("expiresAt").notNull(),
  },
  (table) => ({
    expiresAtIdx: index("spent_nonces_expires_at_idx").on(table.expiresAt),
  }),
);

/** Agent pairing credentials, so any replica redeems what another showed (lib/agent/pairing-codes.ts). */
export const agentPairingSecrets = sqliteTable("agent_pairing_secrets", {
  /** `code`, `repair:<agentId>` or `bootstrap`. */
  slot: text("slot").primaryKey(),
  /** A code encrypted, since the page shows it again; a bootstrap token's SHA-256. */
  secret: text("secret").notNull(),
  /** The one agent a bootstrap token may pair; null for a never-seen one. */
  agentId: text("agentId"),
  expiresAt: integer("expiresAt").notNull(),
  failures: integer("failures").notNull().default(0),
});

/** Which replica holds each agent's stream (lib/agent/broker.ts); the stream itself is in memory. */
export const agentConnections = sqliteTable(
  "agent_connections",
  {
    agentId: text("agentId").primaryKey(),
    replicaId: text("replicaId").notNull(),
    agentRowId: integer("agentRowId").notNull(),
    /** For messages, never for routing. */
    name: text("name").notNull(),
    /** Fingerprint of the secret the stream authenticated with. */
    credential: text("credential"),
    connectedAt: integer("connectedAt").notNull(),
    lastSeenAt: integer("lastSeenAt").notNull(),
    /** The agent's last AgentStatus, as JSON. */
    status: text("status"),
  },
  (table) => ({
    replicaIdx: index("agent_connections_replica_idx").on(table.replicaId),
  }),
);

/** Server events for an agent whose stream another replica holds; drained by that replica. */
export const agentOutbox = sqliteTable(
  "agent_outbox",
  {
    id: text("id").primaryKey(),
    /** The replica holding the stream when this was written. */
    replicaId: text("replicaId").notNull(),
    agentId: text("agentId").notNull(),
    /** An AgentServerEvent, as JSON. */
    event: text("event").notNull(),
    createdAt: integer("createdAt").notNull(),
  },
  (table) => ({
    replicaIdx: index("agent_outbox_replica_idx").on(table.replicaId),
  }),
);

/** A command's result for the replica that issued it, when the agent answered through another. */
export const agentCommandResults = sqliteTable(
  "agent_command_results",
  {
    commandId: text("commandId").primaryKey(),
    replicaId: text("replicaId").notNull(),
    result: text("result").notNull(),
    createdAt: integer("createdAt").notNull(),
  },
  (table) => ({
    replicaIdx: index("agent_command_results_replica_idx").on(table.replicaId),
  }),
);

/** 502/503/504 answers per proxy host and minute, from whichever replica the agent reported to. */
export const upstreamErrorCounts = sqliteTable(
  "upstream_error_counts",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    proxyHostId: integer("proxyHostId")
      .references(() => proxyHosts.id, { onDelete: "cascade" })
      .notNull(),
    /** Epoch ms at the start of the minute. */
    minute: integer("minute").notNull(),
    count: integer("count").notNull(),
  },
  (table) => ({
    hostMinuteUnique: uniqueIndex("upstream_error_counts_host_minute_unique").on(
      table.proxyHostId,
      table.minute,
    ),
    minuteIdx: index("upstream_error_counts_minute_idx").on(table.minute),
  }),
);

/** The leader's MaxMind downloads, for the other replicas to install (lib/geoip/replicas.ts). */
export const geoipDatabases = sqliteTable("geoip_databases", {
  edition: text("edition").primaryKey(),
  /** Of `data`, so a replica compares hashes rather than reading the file each heartbeat. */
  sha256: text("sha256").notNull(),
  data: binary("data").notNull(),
  updatedAt: text("updatedAt").notNull(),
});

/** Where scheduled backups are written: an S3-compatible bucket or a folder on the data volume. */
export const backupDestinations = sqliteTable(
  "backup_destinations",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    /** `s3` or `local`. */
    kind: text("kind").notNull(),
    /** Empty for AWS itself, where the region picks the host. */
    endpoint: text("endpoint").notNull().default(""),
    region: text("region").notNull().default(""),
    bucket: text("bucket").notNull().default(""),
    /** Prepended to every key, e.g. `cpm/`. */
    prefix: text("prefix").notNull().default(""),
    accessKeyId: text("accessKeyId").notNull().default(""),
    secretAccessKey: text("secretAccessKey").notNull().default(""),
    virtualHostedStyle: integer("virtualHostedStyle", { mode: "boolean" }).notNull().default(false),
    /** For `local`: a folder under the data volume's backups/. */
    path: text("path").notNull().default(""),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    nameUnique: uniqueIndex("backup_destinations_name_unique").on(table.name),
  }),
);

export const backupSchedules = sqliteTable(
  "backup_schedules",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    destinationId: integer("destinationId")
      .references(() => backupDestinations.id, { onDelete: "restrict" })
      .notNull(),
    cron: text("cron").notNull(),
    timeZone: text("timeZone").notNull().default("UTC"),
    /** Under the destination's prefix; retention never looks outside it. */
    prefix: text("prefix").notNull().default(""),
    includeAuditLog: integer("includeAuditLog", { mode: "boolean" }).notNull().default(false),
    includeSettingsHistory: integer("includeSettingsHistory", { mode: "boolean" })
      .notNull()
      .default(false),
    keepLast: integer("keepLast"),
    keepDays: integer("keepDays"),
    /** Encrypted, so a run needs nobody present. */
    passphrase: text("passphrase").notNull(),
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    /** When the timing last changed: catch-up never runs a slot from before it. */
    scheduledSince: text("scheduledSince").notNull(),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    nameUnique: uniqueIndex("backup_schedules_name_unique").on(table.name),
  }),
);

/** One row per slot, claimed before the run starts, so a leadership flip never runs it twice. */
export const backupRuns = sqliteTable(
  "backup_runs",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    scheduleId: integer("scheduleId")
      .references(() => backupSchedules.id, { onDelete: "cascade" })
      .notNull(),
    /** Epoch ms of the cron occurrence; a manual run's own start. */
    slot: integer("slot").notNull(),
    /** `schedule`, `catch-up` or `manual`. */
    trigger: text("trigger").notNull(),
    /** `running`, `succeeded` or `failed`. */
    status: text("status").notNull(),
    objectKey: text("objectKey"),
    bytes: integer("bytes"),
    durationMs: integer("durationMs"),
    error: text("error"),
    errorCode: text("errorCode"),
    replica: text("replica"),
    startedAt: text("startedAt").notNull(),
    finishedAt: text("finishedAt"),
  },
  (table) => ({
    slotUnique: uniqueIndex("backup_runs_schedule_slot_unique").on(table.scheduleId, table.slot),
    startedIdx: index("backup_runs_started_at_idx").on(table.startedAt),
  }),
);

/**
 * A full snapshot after every proxy and L4 host write, in that write's transaction. No foreign key
 * to the host: a deleted host's last revision is what restores it.
 */
export const hostRevisions = sqliteTable(
  "host_revisions",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    /** `http` or `l4`. */
    hostKind: text("hostKind").notNull(),
    hostId: integer("hostId").notNull(),
    /** `create`, `update`, `maintenance`, `delete`, `bulk`, `import`, `rollback` or `restore`. */
    operation: text("operation").notNull(),
    /** JSON: the bulk action, or the revision a rollback or restore came from. */
    detail: text("detail"),
    /** JSON `{ row, agentIds }`: the row as stored, secrets still in their `enc:v1` form. */
    snapshot: text("snapshot").notNull(),
    userId: integer("userId").references(() => users.id, { onDelete: "set null" }),
    /** Kept beside the id, so a deleted user's revisions still say who. */
    userName: text("userName"),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    hostIdx: index("host_revisions_host_idx").on(table.hostKind, table.hostId, table.id),
    createdIdx: index("host_revisions_created_at_idx").on(table.createdAt),
  }),
);

// ── Alerts (lib/notifications, lib/alerts) ───────────────────────────

/** Where alerts go. `email` and `push` are built in; the rest an administrator adds. */
export const notificationChannels = sqliteTable(
  "notification_channels",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    /** `email`, `push`, `webhook`, `discord`, `slack`, `teams` or `ntfy`. */
    kind: text("kind").notNull(),
    /** `email` or `push` for the two every install has; null for one an administrator added. */
    builtin: text("builtin"),
    /** JSON of what may be shown back: ntfy's server and topic, a webhook's header names. */
    config: text("config").notNull().default("{}"),
    /** `enc:v1` JSON of what may not: URLs that embed a token, signing keys, header values. */
    secret: text("secret").notNull().default(""),
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    /** Failed sends in a row; the backoff grows with it. */
    failures: integer("failures").notNull().default(0),
    /** No send before this, after a failed one. */
    retryAt: text("retryAt"),
    lastSentAt: text("lastSentAt"),
    /** As the receiver said it, in English; null after a good send. */
    lastError: text("lastError"),
    lastErrorAt: text("lastErrorAt"),
    /** `noRecipients` when there was nobody to send to. */
    lastErrorCode: text("lastErrorCode"),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    nameUnique: uniqueIndex("notification_channels_name_unique").on(table.name),
    builtinUnique: uniqueIndex("notification_channels_builtin_unique").on(table.builtin),
  }),
);

/**
 * What is worth telling, and where. Each notification category is a built-in rule whose on switch
 * stays its Settings toggle, so an upgrade changes nothing until someone edits one.
 */
export const alertRules = sqliteTable(
  "alert_rules",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    /** The category a built-in rule stands for; null for one an administrator added. */
    builtin: text("builtin"),
    /** `event`, `attention`, `signal` or `metric`. */
    source: text("source").notNull(),
    /** JSON, by source: event kinds, an attention code, a signal kind, a metric threshold. */
    sourceConfig: text("sourceConfig").notNull().default("{}"),
    /** `all`, `hosts` or `tags`. */
    scope: text("scope").notNull().default("all"),
    /** JSON: proxy host ids, or tags. */
    scopeValues: text("scopeValues").notNull().default("[]"),
    /** `critical`, `warning` or `info`. */
    severity: text("severity").notNull().default("warning"),
    /** JSON channel ids; deleting a channel takes it out of every rule in the same transaction. */
    channelIds: text("channelIds").notNull().default("[]"),
    /** After telling, the same rule stays quiet about the same thing this long. */
    quietMinutes: integer("quietMinutes").notNull().default(0),
    /** Ignored for a built-in rule: its Settings switch decides. */
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    silencedUntil: text("silencedUntil"),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    builtinUnique: uniqueIndex("alert_rules_builtin_unique").on(table.builtin),
  }),
);

/** Per deduplication key: a problem still open, a quiet period, a failure streak. */
export const alertKeys = sqliteTable("alert_keys", {
  key: text("key").primaryKey(),
  /** Set while a problem raised under this key is not over. */
  openAt: text("openAt"),
  /** JSON: the event that raised it, for the recovery to name the same thing. */
  openEvent: text("openEvent"),
  /** JSON: the alert_events rows it raised, and the rules they came from. */
  openEventIds: text("openEventIds").notNull().default("[]"),
  openRuleIds: text("openRuleIds").notNull().default("[]"),
  /** ISO, or `never`. */
  quietUntil: text("quietUntil"),
  streak: integer("streak").notNull().default(0),
  updatedAt: text("updatedAt").notNull(),
});

/** Every alert raised, resolved or told once: one row per rule it matched. */
export const alertEvents = sqliteTable(
  "alert_events",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    key: text("key").notNull(),
    ruleId: integer("ruleId").references(() => alertRules.id, { onDelete: "set null" }),
    kind: text("kind").notNull(),
    category: text("category"),
    severity: text("severity").notNull(),
    /** `notice`, `problem` or `recovery`. */
    type: text("type").notNull(),
    /** JSON NotificationEvent. */
    event: text("event").notNull(),
    at: text("at").notNull(),
    /** For a problem: when it was over. */
    resolvedAt: text("resolvedAt"),
  },
  (table) => ({
    atIdx: index("alert_events_at_idx").on(table.at),
    ruleKeyIdx: index("alert_events_rule_key_idx").on(table.ruleId, table.key),
  }),
);

/**
 * One event to one channel. Claimed before it is sent, so two workers never both send it; an
 * expired claim is a worker that died, and the row is sent again.
 */
export const alertDeliveries = sqliteTable(
  "alert_deliveries",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    eventId: integer("eventId")
      .references(() => alertEvents.id, { onDelete: "cascade" })
      .notNull(),
    channelId: integer("channelId")
      .references(() => notificationChannels.id, { onDelete: "cascade" })
      .notNull(),
    /** `pending`, `sent`, `failed`, `dropped` or `withdrawn`. */
    status: text("status").notNull().default("pending"),
    attempts: integer("attempts").notNull().default(0),
    lastError: text("lastError"),
    /** JSON: recipients a partly failed send already reached, so a retry skips them. */
    reached: text("reached").notNull().default("[]"),
    claimedBy: text("claimedBy"),
    claimedUntil: text("claimedUntil"),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
    sentAt: text("sentAt"),
  },
  (table) => ({
    eventChannelUnique: uniqueIndex("alert_deliveries_event_channel_unique").on(
      table.eventId,
      table.channelId,
    ),
    channelStatusIdx: index("alert_deliveries_channel_status_idx").on(
      table.channelId,
      table.status,
    ),
  }),
);

/** A daily report: when, in which zone, to which channels. */
export const alertDigests = sqliteTable(
  "alert_digests",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    /** `HH:MM`, read in timeZone. */
    time: text("time").notNull(),
    timeZone: text("timeZone").notNull().default("UTC"),
    channelIds: text("channelIds").notNull().default("[]"),
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    /** When the timing last changed: catch-up never sends a slot from before it. */
    scheduledSince: text("scheduledSince").notNull(),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    nameUnique: uniqueIndex("alert_digests_name_unique").on(table.name),
  }),
);

/** One row per digest slot, claimed before anything is sent. */
export const alertDigestRuns = sqliteTable(
  "alert_digest_runs",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    digestId: integer("digestId")
      .references(() => alertDigests.id, { onDelete: "cascade" })
      .notNull(),
    /** Epoch ms of the occurrence; a "send now" run's own start. */
    slot: integer("slot").notNull(),
    /** `schedule`, `catch-up` or `manual`. */
    trigger: text("trigger").notNull(),
    /** `running`, `sent`, `partial` or `failed`. */
    status: text("status").notNull(),
    /** JSON: per channel, whether it went and why not. */
    results: text("results").notNull().default("[]"),
    error: text("error"),
    replica: text("replica"),
    startedAt: text("startedAt").notNull(),
    finishedAt: text("finishedAt"),
  },
  (table) => ({
    slotUnique: uniqueIndex("alert_digest_runs_digest_slot_unique").on(table.digestId, table.slot),
  }),
);

// ── Audit streaming (lib/audit-stream) ───────────────────────────────

/** Where the audit log is streamed: syslog over UDP, TCP or TLS, HTTP, or a file. */
export const auditSinks = sqliteTable(
  "audit_sinks",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    name: text("name").notNull(),
    /** `syslog-udp`, `syslog-tcp`, `syslog-tls`, `http` or `file`. */
    kind: text("kind").notNull(),
    enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
    /** JSON of what may be shown back: host, port, URL, encoding, file name, size limit, CA. */
    config: text("config").notNull().default("{}"),
    /** `enc:v1` JSON of the HTTP auth header's value. */
    secret: text("secret").notNull().default(""),
    /** WAF events and other mitigated requests, outside the hash chain. */
    includeSecurity: integer("includeSecurity", { mode: "boolean" }).notNull().default(false),
    /** The last audit `seq` delivered. */
    auditCursor: integer("auditCursor").notNull().default(0),
    /** The last security record delivered (audit_security_records.seq). */
    securityCursor: integer("securityCursor").notNull().default(0),
    /** After a 415: requests go uncompressed until the sink is saved again. */
    encodingFallback: integer("encodingFallback", { mode: "boolean" }).notNull().default(false),
    /** Failed passes in a row; the backoff grows with it. */
    failures: integer("failures").notNull().default(0),
    retryAt: text("retryAt"),
    lastDeliveredAt: text("lastDeliveredAt"),
    lastError: text("lastError"),
    lastErrorAt: text("lastErrorAt"),
    /** JSON StoredErrorCode, so the page renders lastError in the reader's language. */
    lastErrorCode: text("lastErrorCode"),
    /** The latest records pruned before this sink took them: `audit` or `security`, and seqs. */
    gapStream: text("gapStream"),
    gapFrom: integer("gapFrom"),
    gapTo: integer("gapTo"),
    gapAt: text("gapAt"),
    /** Records lost to gaps, in total. */
    missed: integer("missed").notNull().default(0),
    /** The replica delivering, so a leadership flip never has two sending at once. */
    leaseOwner: text("leaseOwner"),
    leaseUntil: text("leaseUntil"),
    createdAt: text("createdAt").notNull(),
    updatedAt: text("updatedAt").notNull(),
  },
  (table) => ({
    nameUnique: uniqueIndex("audit_sinks_name_unique").on(table.name),
  }),
);

/**
 * Security records waiting for the sinks that include them, queued at ingest while any does.
 * `seq` is handed out under the head row's lock, so it is commit order.
 */
export const auditSecurityRecords = sqliteTable(
  "audit_security_records",
  {
    seq: integer("seq").primaryKey(),
    /** The record as streamed, JSON, redacted as stored. */
    record: text("record").notNull(),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    createdAtIdx: index("audit_security_records_created_at_idx").on(table.createdAt),
  }),
);

/** One row (id 1): the last security `seq` handed out, and how far pruning has gone. */
export const auditSecurityHead = sqliteTable("audit_security_head", {
  id: integer("id").primaryKey(),
  headSeq: integer("headSeq").notNull().default(0),
  prunedSeq: integer("prunedSeq").notNull().default(0),
  updatedAt: text("updatedAt").notNull(),
});

// ── Access reviews (lib/access-reviews) ──────────────────────────────

/** A campaign asking reviewers whether each piece of access in its scope should stay. */
export const accessReviewCampaigns = sqliteTable("access_review_campaigns", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  /** allUsers, role, group, grants, tokens or scim. */
  scope: text("scope").notNull(),
  /** The role key or group id a role or group scope names. */
  scopeRef: text("scopeRef"),
  /** YYYY-MM-DD; due at the end of that day, UTC. */
  dueOn: text("dueOn").notNull(),
  /** open, confirming (revocations wait for an administrator) or closed. */
  status: text("status").notNull().default("open"),
  createdBy: integer("createdBy").references(() => users.id, { onDelete: "set null" }),
  closedBy: integer("closedBy").references(() => users.id, { onDelete: "set null" }),
  closedAt: text("closedAt"),
  appliedBy: integer("appliedBy").references(() => users.id, { onDelete: "set null" }),
  appliedAt: text("appliedAt"),
  createdAt: text("createdAt").notNull(),
  updatedAt: text("updatedAt").notNull(),
});

/**
 * One piece of access under review, with the names it had when the campaign opened, so the export
 * still reads after the account, group or token is gone.
 */
export const accessReviewItems = sqliteTable(
  "access_review_items",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    campaignId: integer("campaignId")
      .references(() => accessReviewCampaigns.id, { onDelete: "cascade" })
      .notNull(),
    /** role, membership, grant, token or scimConnection. */
    kind: text("kind").notNull(),
    userId: integer("userId").references(() => users.id, { onDelete: "set null" }),
    groupId: integer("groupId").references(() => groups.id, { onDelete: "set null" }),
    tokenId: integer("tokenId").references(() => apiTokens.id, { onDelete: "set null" }),
    connectionId: integer("connectionId").references(() => scimConnections.id, {
      onDelete: "set null",
    }),
    /** A grant's object: proxyHost, l4ProxyHost or agent, and its id. */
    objectKind: text("objectKind"),
    objectId: integer("objectId"),
    subjectLabel: text("subjectLabel").notNull(),
    targetLabel: text("targetLabel"),
    /** The role key, or a grant's view or manage. */
    current: text("current"),
    /** JSON array of hint codes, as found when the campaign opened. */
    hints: text("hints").notNull().default("[]"),
    /** The account or group belongs to a SCIM connection, which would undo a revocation. */
    scimManaged: integer("scimManaged", { mode: "boolean" }).notNull().default(false),
    reviewerId: integer("reviewerId").references(() => users.id, { onDelete: "set null" }),
    /** keep, revoke or change; null until decided. */
    decision: text("decision"),
    changeTo: text("changeTo"),
    note: text("note"),
    decidedBy: integer("decidedBy").references(() => users.id, { onDelete: "set null" }),
    decidedAt: text("decidedAt"),
    /** applied, failed or gone (nothing left to revoke); null until applied. */
    outcome: text("outcome"),
    outcomeCode: text("outcomeCode"),
    appliedAt: text("appliedAt"),
  },
  (table) => ({
    campaignIdx: index("access_review_items_campaign_idx").on(table.campaignId),
    reviewerIdx: index("access_review_items_reviewer_idx").on(table.reviewerId),
  }),
);

// ── Change approvals (lib/approvals) ─────────────────────────────────

/**
 * A write held for approval: what the save would have sent, sealed, and the diff its approvers
 * read. Applied as the requester once enough approvers agree, unless its target moved since.
 */
export const changeRequests = sqliteTable(
  "change_requests",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    /** proxyHostUpdate, accessListRules, settingsApply... (lib/approvals/kinds.ts). */
    kind: text("kind").notNull(),
    /** hosts, accessLists, waf or settings. */
    area: text("area").notNull(),
    targetType: text("targetType"),
    targetId: integer("targetId"),
    /** The target's name when submitted, so the list still reads after it is gone. */
    targetName: text("targetName"),
    /** `enc:v1` JSON of the write: a host's input can carry credentials. */
    payload: text("payload").notNull(),
    /** JSON: the diff and impact approvers are shown, secrets masked. */
    preview: text("preview").notNull(),
    /** Hash of the target as it stood when submitted; a different one at apply invalidates it. */
    baseState: text("baseState").notNull(),
    /** JSON array: the host tags the request touched, which a tag policy matched on. */
    tags: text("tags").notNull().default("[]"),
    requiredApprovals: integer("requiredApprovals").notNull().default(1),
    /** pending, applying, applied, failed, rejected, withdrawn or invalidated. */
    status: text("status").notNull().default("pending"),
    requestedBy: integer("requestedBy").references(() => users.id, { onDelete: "set null" }),
    requestedByName: text("requestedByName"),
    /** Submitted with an API token, which is why it waits rather than applied. */
    viaToken: integer("viaToken", { mode: "boolean" }).notNull().default(false),
    bypassedBy: integer("bypassedBy").references(() => users.id, { onDelete: "set null" }),
    bypassedByName: text("bypassedByName"),
    bypassReason: text("bypassReason"),
    /** Why it failed or was invalidated: an error code, and the English message. */
    resultCode: text("resultCode"),
    error: text("error"),
    createdAt: text("createdAt").notNull(),
    decidedAt: text("decidedAt"),
    appliedAt: text("appliedAt"),
  },
  (table) => ({
    statusIdx: index("change_requests_status_idx").on(table.status, table.id),
  }),
);

/** One approver's say on a request; one each, so a second click cannot count twice. */
export const changeRequestDecisions = sqliteTable(
  "change_request_decisions",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    requestId: integer("requestId")
      .references(() => changeRequests.id, { onDelete: "cascade" })
      .notNull(),
    userId: integer("userId").references(() => users.id, { onDelete: "set null" }),
    userName: text("userName"),
    /** approve or reject. */
    decision: text("decision").notNull(),
    note: text("note"),
    createdAt: text("createdAt").notNull(),
  },
  (table) => ({
    oneEach: uniqueIndex("change_request_decisions_once").on(table.requestId, table.userId),
  }),
);
